### PR TITLE
Add CockroachDB v22.1 to test matrix.

### PR DESCRIPTION
**Pull request by bobvawter**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/142)

### CODE REVIEW

**Comment by bobvawter** [comment]
The feature-detection is a bit hacky, I want to go find a semver-parsing library and fix this and the other couple of spots where we have version-specific behavior in a future PR.

**Review by sravotto — COMMENTED** [review]
couple of minor things...

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/142#-:-N2sGwYr7d6lMcKDIAgk:brnnsi8)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @bobvawter and @BramGruneir)

___
*[`internal/target/schemawatch/coldata.go` line 105 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/142#-N2sFfejCi14pZzNNWQI:-N2sFfekBZI9Ey2bVrZA:b-7h0r1w) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/26fc55c6f2261f75f5541190fac879fa6ea44be9/internal/target/schemawatch/coldata.go#L105)):*
> ```Go
> 		// If there are no primary key columns, we know that a synthetic
> 		// rowid column will exist. We'll prepend it to the slice and
> 		// then delete the
> ```

Sentence doesn't seem finished...
___
*[`internal/target/sinktest/sinktest.go` line 72 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/142#-N2sGQiKAreJOCMwOx9J:-N2sGQiKAreJOCMwOx9K:b-96suij) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/26fc55c6f2261f75f5541190fac879fa6ea44be9/internal/target/sinktest/sinktest.go#L72)):*
> ```Go
> 	// Reset the pool to one that enables the hash-sharded feature in
> 	// older versions of CockroachDB.
> 	if !strings.Contains(globalDBInfo.version, "v22.") {
> ```

perhaps we should check explicitly that is older for future proofing....

**Review by bobvawter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/142)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @BramGruneir and @sravotto)

___
*[`internal/target/schemawatch/coldata.go` line 105 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/142#-N2sFfejCi14pZzNNWQI:-N3-bJ_T6UZTadkHeBaX:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/26fc55c6f2261f75f5541190fac879fa6ea44be9/internal/target/schemawatch/coldata.go#L105)):*
<details><summary><i>Previously, sravotto (silvano) wrote…</i></summary><blockquote>

Sentence doesn't seem finished...
</blockquote></details>

Done.
___
*[`internal/target/sinktest/sinktest.go` line 72 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/142#-N2sGQiKAreJOCMwOx9J:-N3-bIkcEGwXWqEXYVjM:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/26fc55c6f2261f75f5541190fac879fa6ea44be9/internal/target/sinktest/sinktest.go#L72)):*
<details><summary><i>Previously, sravotto (silvano) wrote…</i></summary><blockquote>

perhaps we should check explicitly that is older for future proofing.... 
</blockquote></details>

Done.

**Review by sravotto — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/142#-:-N3-qXOu5T96iw0eOMmY:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @BramGruneir and @sravotto)

**Pull request merged**
