### PR TITLE
logical: Delete logical package

### PR DESCRIPTION
**Pull request by bobvawter**
This PR is stacked on #681 and #682

This commit removes the logical package and updates the existing users to the
sequencer and related packages.

cdc package: The resolved timestamp and mutation lifecycle code was previously
moved to and expanded upon in the checkpoint and sequencer packages. A new
Targets type is responsible for configuring the sequencer stack that manages a
particular target schema. Of particular note are the Targets.modeSelecter() and
Targets.updateResolved() which replace the previous backfill-selecting and
consistent-point code. The HTTP endpoint code is relatively unchanged,
receiving minor updates to use different type and method names.

The mylogical and pglogical packages are updated and both work the same way.
Instead of the logical loop code, there is a stoppered goroutine that copies
data from a source network connection into an acceptor. A companion goroutine
updates the memo table with the connection's WAL-offset equivalent.

There are some small bugfixes in supporting packages that the suite of CDC
tests identified, mainly related to transaction retries and deferrable errors.
The types.Applier interface has also been completely replaced with the Acceptor
interfaces.

Testing note: The CDC + BestEffort + ConcurrentHandler tests significantly
increased the number of connections being opened to the target database.
Adjustments to the testing pool sizes and maximum connection count for postgres
were necessary.

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/684)

### CODE REVIEW

**Review by BramGruneir — CHANGES_REQUESTED** [review]
> Reviewed 73 of 73 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/684)* status: 73 of 144 files reviewed, 11 unresolved discussions (waiting on @bobvawter)

___
*[`internal/sinkprod/staging.go` line 37 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/684#-NqPfTyv-t9hkmn6QeKG:-NqPfTyw2HObJ08wPxzf:blcdj3y) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a0f768a5f3710c3d693755a11da4044daede1dc3/internal/sinkprod/staging.go#L37)):*
> ```Go
> 	// loadbalancer compatibility.
> 	Lifetime time.Duration
> 	// The number of connections to the target database. If zero, a
> ```

Why not just don't set to get the default?  Is there a reason to include 0 to set to default?
___
*[`internal/source/cdc/config.go` line 43 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/684#-NqPggj01mY-KbxoXZ8j:-NqPggj12k9OzyDMoUWy:b-l2uafa) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a0f768a5f3710c3d693755a11da4044daede1dc3/internal/source/cdc/config.go#L43)):*
> ```Go
> 	// applied resolved timestamp is older than this threshold. A
> 	// negative or zero value will disable BestEffort switching.
> 	BackfillWindow time.Duration
> ```

BestEffortWindow?
___
*[`internal/source/cdc/config.go` line 80 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/684#-NqPgtEFAG3e9rEgmMcs:-NqPgtEG3msAPHgI4GDj:bahncq1) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a0f768a5f3710c3d693755a11da4044daede1dc3/internal/source/cdc/config.go#L80)):*
> ```Go
> 		"the maximum amount of data to buffer while reading a single line of ndjson input; "+
> 			"increase when source cluster has large blob values")
> 	f.BoolVar(&c.Shingle, "shingle", false,
> ```

This should default to true.

Shingling provides the same serializable guarantees that Cockroach does.
___
*[`internal/source/cdc/ndjson_query.go` line 58 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/684#-NqPhNJa8EnTF484ZdBf:-NqPhNJa8EnTF484ZdBg:b-wssni2) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a0f768a5f3710c3d693755a11da4044daede1dc3/internal/source/cdc/ndjson_query.go#L58)):*
> ```Go
> 		return nil, errors.Errorf("expecting ident.Table, got %T", req.target)
> 	}
> 	tgt, err := h.Targets.getTarget(table.Schema())
> ```

might as well just call it target
___
*[`internal/source/cdc/resolved.go` line 66 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/684#-NqPhZ8a3Ea-e7lmnbiv:-NqPhZ8a3Ea-e7lmnbiw:b4pf9p8) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a0f768a5f3710c3d693755a11da4044daede1dc3/internal/source/cdc/resolved.go#L66)):*
> ```Go
> // resolved acts upon a resolved timestamp message.
> func (h *Handler) resolved(ctx context.Context, req *request) error {
> 	tgt, err := h.Targets.getTarget(req.target.Schema())
> ```

again, might as well just call it target, you're not saving much with tgt  (I saw a few tgts too)
___
*[`internal/source/cdc/targets.go` line 207 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/684#-NqPikXZ9Ywt0hgdAVss:-NqPikXZ9Ywt0hgdAVst:bqjorfk) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a0f768a5f3710c3d693755a11da4044daede1dc3/internal/source/cdc/targets.go#L207)):*
> ```Go
> 				lag := time.Since(minTime)
> 
> 				// Sometimes you don't know what you want.
> ```

As in life.
___
*[`internal/source/cdc/webhook.go` line 54 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/684#-NqPkIH9Abot4V4w7o1g:-NqPkIH9Abot4V4w7o1h:b-las52s) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a0f768a5f3710c3d693755a11da4044daede1dc3/internal/source/cdc/webhook.go#L54)):*
> ```Go
> 		return errors.Wrap(err, "could not decode payload")
> 	}
> 	tgt, err := h.Targets.getTarget(req.target.Schema())
> ```

tgt --> target ... you even used target before!
___
*[`internal/source/cdc/webhook_query.go` line 36 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/684#-NqPkOun0Cc2xU-5225U:-NqPkOun0Cc2xU-5225V:b-j4rfwp) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a0f768a5f3710c3d693755a11da4044daede1dc3/internal/source/cdc/webhook_query.go#L36)):*
> ```Go
> func (h *Handler) webhookForQuery(ctx context.Context, req *request) error {
> 	table := req.target.(ident.Table)
> 	tgt, err := h.Targets.getTarget(table.Schema())
> ```

tgt --> target
___
*[`internal/source/cdc/server/config.go` line 17 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/684#-NqPkbH74nD6y7rVEpUC:-NqPkbH74nD6y7rVEpUD:b-cxh7o7) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a0f768a5f3710c3d693755a11da4044daede1dc3/internal/source/cdc/server/config.go#L17)):*
> ```Go
> // SPDX-License-Identifier: Apache-2.0
> 
> package server
> ```

This file is so much cleaner!
___
*[`internal/source/mylogical/conn.go` line 569 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/684#-NqPlwOGEuFULMfO4Snn:-NqPlwOGEuFULMfO4Sno:b7mlrhf) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a0f768a5f3710c3d693755a11da4044daede1dc3/internal/source/mylogical/conn.go#L569)):*
> ```Go
> // in the stopper to occasionally write an updated value back to the
> // memo.
> func (c *conn) persistWALOffset(ctx *stopper.Context) error {
> ```

This could probably use a test.
___
*[`internal/source/pglogical/conn.go` line 430 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/684#-NqPpYoCA3Jj2-TaKdUb:-NqPpYoCA3Jj2-TaKdUc:byo2s5q) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a0f768a5f3710c3d693755a11da4044daede1dc3/internal/source/pglogical/conn.go#L430)):*
> ```Go
> // will also start a goroutine in the stopper to occasionally write an
> // updated value back to the memo.
> func (c *Conn) persistWALOffset(ctx *stopper.Context) error {
> ```

This should probably have a unit test as well.
___
*[`internal/staging/stage/factory.go` line 148 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/684#-NqPqF729qdnjkUEgHKY:-NqPqF729qdnjkUEgHKZ:b-akn0v2) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a0f768a5f3710c3d693755a11da4044daede1dc3/internal/staging/stage/factory.go#L148)):*
> ```Go
> 		return nil
> 	})
> 	if err != nil {
> ```

This can be merged with the function call right?
___
*[`internal/util/applycfg/conf.go` line 68 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/684#-NqPqbgRCF9vUNRDSQQe:-NqPqbgRCF9vUNRDSQQf:b-jk2z0x) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a0f768a5f3710c3d693755a11da4044daede1dc3/internal/util/applycfg/conf.go#L68)):*
> ```Go
> 
> // Copy returns a copy of the Config.
> func (t *Config) Copy() *Config {
> ```

Why are these all t  and not c?
Yes it's not part of this PR per se, but ... eww.

**Review by bobvawter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/684)* status: 0 of 144 files reviewed, 11 unresolved discussions (waiting on @BramGruneir)

___
*[`internal/sinkprod/staging.go` line 37 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/684#-NqPfTyv-t9hkmn6QeKG:-NqThLsk8XTK4VYCqQE6:b-hznhnp) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a0f768a5f3710c3d693755a11da4044daede1dc3/internal/sinkprod/staging.go#L37)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why not just don't set to get the default?  Is there a reason to include 0 to set to default?
</blockquote></details>

The zero-means-default behavior is useful in tests when the configurations are being partially initialized and then pre-flighted.
___
*[`internal/source/cdc/config.go` line 43 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/684#-NqPggj01mY-KbxoXZ8j:-NqTg510B3QyPbCBO2T8:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a0f768a5f3710c3d693755a11da4044daede1dc3/internal/source/cdc/config.go#L43)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

BestEffortWindow?
</blockquote></details>

Done.
___
*[`internal/source/cdc/config.go` line 80 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/684#-NqPgtEFAG3e9rEgmMcs:-NqTg5Xn91XdbT1rp4y5:b-d8vwrf) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a0f768a5f3710c3d693755a11da4044daede1dc3/internal/source/cdc/config.go#L80)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This should default to true.

Shingling provides the same serializable guarantees that Cockroach does.
</blockquote></details>

I have removed this as an explicit point of configuration.  `ModeShingle` is now the default unless parallelism is set to 1.
___
*[`internal/source/cdc/ndjson_query.go` line 58 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/684#-NqPhNJa8EnTF484ZdBf:-NqTgVHR9VTZuw7cGJ2l:bmb98js) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a0f768a5f3710c3d693755a11da4044daede1dc3/internal/source/cdc/ndjson_query.go#L58)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

might as well just call it target
</blockquote></details>

Fixed here and elsewhere.
___
*[`internal/source/cdc/resolved.go` line 66 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/684#-NqPhZ8a3Ea-e7lmnbiv:-NqTgkQy6HxXisPZmV99:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a0f768a5f3710c3d693755a11da4044daede1dc3/internal/source/cdc/resolved.go#L66)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

again, might as well just call it target, you're not saving much with tgt  (I saw a few tgts too)
</blockquote></details>

Done.
___
*[`internal/source/cdc/webhook.go` line 54 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/684#-NqPkIH9Abot4V4w7o1g:-NqTgllh1j1oRjwcz6Xy:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a0f768a5f3710c3d693755a11da4044daede1dc3/internal/source/cdc/webhook.go#L54)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

tgt --> target ... you even used target before!
</blockquote></details>

Done.
___
*[`internal/source/cdc/webhook_query.go` line 36 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/684#-NqPkOun0Cc2xU-5225U:-NqTgmRc42nct6ronsCE:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a0f768a5f3710c3d693755a11da4044daede1dc3/internal/source/cdc/webhook_query.go#L36)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

tgt --> target
</blockquote></details>

Done.
___
*[`internal/source/mylogical/conn.go` line 569 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/684#-NqPlwOGEuFULMfO4Snn:-NqTq2dF0BGxRU_juIxq:b70dmdg) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a0f768a5f3710c3d693755a11da4044daede1dc3/internal/source/mylogical/conn.go#L569)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This could probably use a test.
</blockquote></details>

Done.

Verified that a wal record is written at the end of the integration test.
___
*[`internal/source/pglogical/conn.go` line 430 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/684#-NqPpYoCA3Jj2-TaKdUb:-NqTq6Ag5PgGpHI2ZhTk:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a0f768a5f3710c3d693755a11da4044daede1dc3/internal/source/pglogical/conn.go#L430)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This should probably have a unit test as well.
</blockquote></details>

Done.
___
*[`internal/staging/stage/factory.go` line 148 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/684#-NqPqF729qdnjkUEgHKY:-NqTh3RR6SelYiYkD7Bn:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a0f768a5f3710c3d693755a11da4044daede1dc3/internal/staging/stage/factory.go#L148)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This can be merged with the function call right?
</blockquote></details>

Done.
___
*[`internal/util/applycfg/conf.go` line 68 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/684#-NqPqbgRCF9vUNRDSQQe:-NqThA5FADoIew0gHgZI:b1rzv0s) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a0f768a5f3710c3d693755a11da4044daede1dc3/internal/util/applycfg/conf.go#L68)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why are these all t  and not c?
Yes it's not part of this PR per se, but ... eww.
</blockquote></details>

I think that at one point in time the type had been named "Target" or "Table".  I do wish that GoLand would suggest also renaming receivers when a type is renamed.

**Review by BramGruneir — APPROVED** [review]
> Reviewed 11 of 72 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/684)* status: 11 of 144 files reviewed, 1 unresolved discussion (waiting on @bobvawter)

___
*[`internal/util/applycfg/conf.go` line 68 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/684#-NqPqbgRCF9vUNRDSQQe:-NqUWC792-J6Ttv7ipVX:b-ykabht) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a0f768a5f3710c3d693755a11da4044daede1dc3/internal/util/applycfg/conf.go#L68)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

I think that at one point in time the type had been named "Target" or "Table".  I do wish that GoLand would suggest also renaming receivers when a type is renamed.
</blockquote></details>

Can you file a quick cleanup issue to fix this as a follow up PR?

**Review by BramGruneir — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/684#-:-NqUWVCw9x-q9m7_nnnu:bnfp4nl)* status: 11 of 144 files reviewed, 1 unresolved discussion (waiting on @bobvawter)

**Pull request merged**
