### PR TITLE
schemawatch: fix dependency query for constraints using different schema

### PR DESCRIPTION
**Pull request by sravotto**
In the depOrderTemplatePg the where clause within the refs subquery has a redundant check for table_catalog, 
which should be a check for table_schema matching.

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/502)

### CODE REVIEW

**Comment by bobvawter** [comment]
Please write a complete commit message and add a test that fails under the old behavior.

**Comment by bobvawter** [comment]
https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages is what we should base our standards on.

**Review by sravotto — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/502#-:-NfW93df1q8ll1NdXrSQ:b-896fix)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @bobvawter)

**Review by bobvawter — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/502)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @sravotto)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/502#-NfWGBwPDTTXf89vwoOD):*
Typo `redundant`

Word-wrap at 80 chars.
___
*[`internal/target/schemawatch/dependencies.go` line 279 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/502#-NfWFWZP7oOV3gcqjLVr:-NfWFWZP7oOV3gcqjLVs:bknpfxr) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/1dc5b72ec0c74c58de666820c1d2f27c2d171d47/internal/target/schemawatch/dependencies.go#L279)):*
> ```Go
> 
> 			// Allow skipping a level. This might happen if there
> 			// are references across schemas.
> ```

Makes sense. Empty levels won't break current consumers, but it is weird.
___
*[`internal/target/schemawatch/dependencies_test.go` line 201 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/502#-NfWFxb52tKoOIcNSBdb:-NfWFxb60ncte2DpRYX6:b7s3eiv) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/1dc5b72ec0c74c58de666820c1d2f27c2d171d47/internal/target/schemawatch/dependencies_test.go#L201)):*
> ```Go
> }
> 
> func TestDifferentSchema(t *testing.T) {
> ```

`TestCrossSchemaTableReferencesPG`
___
*[`internal/target/schemawatch/dependencies_test.go` line 212 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/502#-NfWF8Yp292kHhDjnm0Y:-NfWF8Yp292kHhDjnm0Z:b-z4uzvx) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/1dc5b72ec0c74c58de666820c1d2f27c2d171d47/internal/target/schemawatch/dependencies_test.go#L212)):*
> ```Go
> 	pool := fixture.TargetPool
> 	switch pool.Product {
> 	// TODO (Silvano) add CRDB when https://github.com/cockroachdb/cockroach/issues/111419 is fixed.
> ```

It would be worth writing this case, even though CRDB returns the wrong data, if only to document what cdc-sink will do in this case.  There are some other tests in cdc-sink that will break if/when certain bugs in CRDB are fixed.
___
*[`internal/target/schemawatch/dependencies_test.go` line 232 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/502#-NfWFf8I38n2xiZDXl_c:-NfWFf8I38n2xiZDXl_d:bqd3h0q) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/1dc5b72ec0c74c58de666820c1d2f27c2d171d47/internal/target/schemawatch/dependencies_test.go#L232)):*
> ```Go
> 		case 0:
> 			r.Equal(1, len(tables))
> 			a.Equal(fmt.Sprintf(`%[1]s."parent"`, fixture.TargetSchema), tables[0].Canonical().String())
> ```

Use `a.True(ident.Equal(...))` instead of this string manipulation.

**Review by sravotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/502)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @bobvawter)

___
*[`internal/target/schemawatch/dependencies.go` line 279 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/502#-NfWFWZP7oOV3gcqjLVr:-NfXU1lk8KT524yo26Yn:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/1dc5b72ec0c74c58de666820c1d2f27c2d171d47/internal/target/schemawatch/dependencies.go#L279)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Makes sense. Empty levels won't break current consumers, but it is weird.
</blockquote></details>

Done.
___
*[`internal/target/schemawatch/dependencies_test.go` line 201 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/502#-NfWFxb52tKoOIcNSBdb:-NfXU3pm5HXqnvqIYZou:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/1dc5b72ec0c74c58de666820c1d2f27c2d171d47/internal/target/schemawatch/dependencies_test.go#L201)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

`TestCrossSchemaTableReferencesPG`
</blockquote></details>

Done.
___
*[`internal/target/schemawatch/dependencies_test.go` line 212 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/502#-NfWF8Yp292kHhDjnm0Y:-NfXU5dR3Kl9KTwR9Cm7:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/1dc5b72ec0c74c58de666820c1d2f27c2d171d47/internal/target/schemawatch/dependencies_test.go#L212)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

It would be worth writing this case, even though CRDB returns the wrong data, if only to document what cdc-sink will do in this case.  There are some other tests in cdc-sink that will break if/when certain bugs in CRDB are fixed.
</blockquote></details>

Done.
___
*[`internal/target/schemawatch/dependencies_test.go` line 232 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/502#-NfWFf8I38n2xiZDXl_c:-NfXU7Kn7zwxzOn2t6CP:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/1dc5b72ec0c74c58de666820c1d2f27c2d171d47/internal/target/schemawatch/dependencies_test.go#L232)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Use `a.True(ident.Equal(...))` instead of this string manipulation.
</blockquote></details>

Done.

**Review by bobvawter — APPROVED** [review]
:lgtm: with the one comment about using the existing query that does return the correct information. There's no overwhelming need to use the `information_schema` query with CRDB, it just seemed like the thing to do if/when we retire support for v21.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/502#-:-NfkSLayCSYeiLxswCVU:bx7sl71)* status: all files reviewed, 1 unresolved discussion (waiting on @sravotto)

___
*[`internal/target/schemawatch/dependencies_test.go` line 241 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/502#-NfkQYjq5RpNgbBXDzu6:-NfkQYjq5RpNgbBXDzu7:b-zcwaje) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/1865cb8fa9db324f12f2c77066707a59a828257c/internal/target/schemawatch/dependencies_test.go#L241)):*
> ```Go
> 	r.NoError(fixture.Watcher.Refresh(ctx, pool))
> 	snap := fixture.Watcher.Get()
> 	if pool.Product == types.ProductCockroachDB && !strings.Contains(pool.Version, "v21.") {
> ```

If the CRDB-specific query that uses the custom porcelain already returns the correct information in the cross-schema case, we should use it, with a note to try to move back to `information_schema` in a future release of CRDB.  Update the `case` statement in `getDependency()` order with a note.

**Review by sravotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/502)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @bobvawter)

___
*[`internal/target/schemawatch/dependencies_test.go` line 241 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/502#-NfkQYjq5RpNgbBXDzu6:-Nfkh5ZL046-r6uoZAZ4:b321iu4) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/1865cb8fa9db324f12f2c77066707a59a828257c/internal/target/schemawatch/dependencies_test.go#L241)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

If the CRDB-specific query that uses the custom porcelain already returns the correct information in the cross-schema case, we should use it, with a note to try to move back to `information_schema` in a future release of CRDB.  Update the `case` statement in `getDependency()` order with a note.
</blockquote></details>

Good point. I fixed it.

**Pull request merged**
