### PR TITLE
conveyor: introducing an abstraction for delivering mutations to a target.

### PR DESCRIPTION
**Pull request by sravotto**
This change moves the logic from cdc.Targets into its own package (named conveyor), since it contains logic that can be re-used to deliver mutations to a target. The delivery mechanisms may use different mode of operations (defined by the underlying sequencer) and spawn multiple partitions within the same table group.

Depending on the mode of operations, mutation can be applied according to checkpoints that are aggregated across multiple partitions.

Breaking Change:

The following metrics have been renamed, dropping the "cdc_" prefix in
favor of a new label kind="cdc":
 
    cdc_mutations_error_count
    cdc_mutations_received_count
    cdc_mutations_success_count
    cdc_source_lag_seconds
    cdc_target_lag_seconds
    cdc_target_applied_timestamp_seconds
    cdc_target_pending_timestamp_seconds

- - -
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/842)

### CODE REVIEW

**Review by bobvawter — COMMENTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/842)* status: all files reviewed, 12 unresolved discussions (waiting on @sravotto)

___
*[`internal/conveyor/config.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-NwpF_3s2_WvUQxOQff2:-NwpF_3s2_WvUQxOQff3:bks3e8l) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/d7212dec15e869f2e99632032effd43a83297728/internal/conveyor/config.go#L56)):*
This comment was stale to begin with; that interface was removed some time ago.

> Preflight ensures the Config is in a known-good state.
___
*[`internal/source/cdc/config.go` line 42 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-NwpGvuJBVi_zRT8AvfA:-NwpGvuJBVi_zRT8AvfB:brsq8f1) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/d7212dec15e869f2e99632032effd43a83297728/internal/source/cdc/config.go#L42)):*
> ```Go
> 	SequencerConfig sequencer.Config
> 	ScriptConfig    script.Config
> 	ConveyorConfig  conveyor.Config
> ```

Sort order.
___
*[`internal/source/cdc/config.go` line 66 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-NwpGxtQ7zKGbovC4i3S:-NwpGxtQ7zKGbovC4i3T:b-80xfat) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/d7212dec15e869f2e99632032effd43a83297728/internal/source/cdc/config.go#L66)):*
> ```Go
> 	c.SequencerConfig.Bind(f)
> 	c.ScriptConfig.Bind(f)
> 	c.ConveyorConfig.Bind(f)
> ```

Sort.
___
*[`internal/source/cdc/config.go` line 90 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-NwpGz0TDOMqSnvmiXYc:-NwpGz0TDOMqSnvmiXYd:b-80xfat) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/d7212dec15e869f2e99632032effd43a83297728/internal/source/cdc/config.go#L90)):*
> ```Go
> 		return err
> 	}
> 	if err := c.ConveyorConfig.Preflight(); err != nil {
> ```

Sort.
___
*[`internal/source/cdc/handler.go` line 49 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-NwpH-QE4oDRLTZLlzG8:-NwpH-QE4oDRLTZLlzG9:b-80xfat) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/d7212dec15e869f2e99632032effd43a83297728/internal/source/cdc/handler.go#L49)):*
> ```Go
> 	Config        *Config             // Runtime options.
> 	TargetPool    *types.TargetPool   // Access to the target cluster.
> 	Conveyors     *conveyor.Conveyors // Mutation delivery to the cluster.
> ```

Sort.
___
*[`internal/source/cdc/provider.go` line 58 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-NwpH6XK6xGzelhUGKFM:-NwpH6XK6xGzelhUGKFN:b6ygcj2) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/d7212dec15e869f2e99632032effd43a83297728/internal/source/cdc/provider.go#L58)):*
> ```Go
> 
> // ProvideConveyors is called by Wire.
> func ProvideConveyors(
> ```

Hoist this into the conveyor package.
___
*[`internal/source/cdc/resolved.go` line 72 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-NwpHNxJ9hhaOfiEWTBW:-NwpHNxJ9hhaOfiEWTBX:b82o7xr) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/d7212dec15e869f2e99632032effd43a83297728/internal/source/cdc/resolved.go#L72)):*
> ```Go
> 		return err
> 	}
> 	return target.Advance(ctx, ident.New(schema.Canonical().Raw()), req.timestamp)
> ```

I don't like how the caller must be responsible for using a canonicalized id. The `Advance()` method should accept `schema` and then perform the canonicalization internally.
___
*[`internal/source/cdc/test_fixture.go` line 45 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-NwpH_U-Eew5mrVQ_vzF:-NwpH_U-Eew5mrVQ_vzG:brsq8f1) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/d7212dec15e869f2e99632032effd43a83297728/internal/source/cdc/test_fixture.go#L45)):*
> ```Go
> 	BestEffort *besteffort.BestEffort
> 	Handler    *Handler
> 	Conveyors  *conveyor.Conveyors
> ```

Sort order.
___
*[`internal/conveyor/conveyor.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-NwpFoVC28KHr4JHXS3T:-NwpFoVC28KHr4JHXS3U:b-45d7yq) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/d7212dec15e869f2e99632032effd43a83297728/internal/conveyor/conveyor.go#L41)):*
> ```Go
> // Conveyors manages the plumbing necessary to deliver mutations
> // to a target schema across multiple partitions.
> // It is also responsible for mode-switching.
> ```

Rewrap all comments at 72 chars.  In Goland, use the "Wrap to Column" plugin to make this effortless.
___
*[`internal/conveyor/conveyor.go` line 45 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-NwpFxy3EVtR6SL2CcKc:-NwpFxy3EVtR6SL2CcKd:b-xu22t3) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/d7212dec15e869f2e99632032effd43a83297728/internal/conveyor/conveyor.go#L45)):*
> ```Go
> 	Cfg           *Config
> 	Checkpoints   *checkpoint.Checkpoints
> 	Kind          string
> ```

This type should be initialized via Wire, ideally making these fields private.  Since the kind must be configured by the user, it would make sense to have a `WithKind()` method that returns a shallow copy of the struct.
___
*[`internal/conveyor/conveyor.go` line 141 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-NwpGZ5R-s-kR9J5uIgz:-NwpGZ5R-s-kR9J5uIh-:brsq8f1) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/d7212dec15e869f2e99632032effd43a83297728/internal/conveyor/conveyor.go#L141)):*
> ```Go
> // and it manages checkpoints across multiple partitions for a table group.
> type Conveyor struct {
> 	factory        *Conveyors                  // Factory that created this conveyor.
> ```

Sort order.
___
*[`internal/conveyor/metrics.go` line 26 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-NwpGk2e6Ix2XrgKrMBG:-NwpGk2e6Ix2XrgKrMBH:b376gjl) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/d7212dec15e869f2e99632032effd43a83297728/internal/conveyor/metrics.go#L26)):*
> ```Go
> var (
> 	mutationsErrorCount = promauto.NewCounterVec(prometheus.CounterOpts{
> 		Name: "mutations_error_count",
> ```

In the commit message, call this out as a breaking change.  I haven't seen anyone use a dashboard other than the one we ship, so this shouldn't be a big problem at the moment.

**Review by sravotto — COMMENTED** [review]
Please take another look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-:-NwprBQT959Z-rxTzgtd:b1xog4q)* status: 8 of 18 files reviewed, 12 unresolved discussions (waiting on @bobvawter)

___
*[`internal/conveyor/config.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-NwpF_3s2_WvUQxOQff2:-NwpqKol94h63URs9Fzs:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/d7212dec15e869f2e99632032effd43a83297728/internal/conveyor/config.go#L56)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

This comment was stale to begin with; that interface was removed some time ago.

> Preflight ensures the Config is in a known-good state.
</blockquote></details>

Done.
___
*[`internal/source/cdc/config.go` line 42 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-NwpGvuJBVi_zRT8AvfA:-NwpqUgb6EphIN31_kyi:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/d7212dec15e869f2e99632032effd43a83297728/internal/source/cdc/config.go#L42)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Sort order.
</blockquote></details>

Done.
___
*[`internal/source/cdc/config.go` line 66 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-NwpGxtQ7zKGbovC4i3S:-NwpqVWx3OygfTnNQz7G:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/d7212dec15e869f2e99632032effd43a83297728/internal/source/cdc/config.go#L66)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Sort.
</blockquote></details>

Done.
___
*[`internal/source/cdc/config.go` line 90 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-NwpGz0TDOMqSnvmiXYc:-NwpqWc03FsSegHHqGlJ:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/d7212dec15e869f2e99632032effd43a83297728/internal/source/cdc/config.go#L90)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Sort.
</blockquote></details>

Done.
___
*[`internal/source/cdc/handler.go` line 49 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-NwpH-QE4oDRLTZLlzG8:-NwpqXwP5FwRRkG-m5yS:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/d7212dec15e869f2e99632032effd43a83297728/internal/source/cdc/handler.go#L49)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Sort.
</blockquote></details>

Done.
___
*[`internal/source/cdc/provider.go` line 58 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-NwpH6XK6xGzelhUGKFM:-NwpqZf691a-6Y_jmXML:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/d7212dec15e869f2e99632032effd43a83297728/internal/source/cdc/provider.go#L58)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Hoist this into the conveyor package.
</blockquote></details>

Done.
___
*[`internal/source/cdc/resolved.go` line 72 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-NwpHNxJ9hhaOfiEWTBW:-Nwpq_nE-KsGRhQUXsKa:b-5627rj) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/d7212dec15e869f2e99632032effd43a83297728/internal/source/cdc/resolved.go#L72)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

I don't like how the caller must be responsible for using a canonicalized id. The `Advance()` method should accept `schema` and then perform the canonicalization internally.
</blockquote></details>

So Advance expects an `Ident` (as a partition). I'm thinking that for cdc (as it is now) we are not really requiring anything. Can't we just pass an empty Ident, until we support multiple CDC feed per schema?
___
*[`internal/source/cdc/test_fixture.go` line 45 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-NwpH_U-Eew5mrVQ_vzF:-Nwpr8Ld2qqX3KR1pFP6:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/d7212dec15e869f2e99632032effd43a83297728/internal/source/cdc/test_fixture.go#L45)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Sort order.
</blockquote></details>

Done.
___
*[`internal/conveyor/conveyor.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-NwpFoVC28KHr4JHXS3T:-NwpqMRf0PkCHbGJiu4T:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/d7212dec15e869f2e99632032effd43a83297728/internal/conveyor/conveyor.go#L41)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Rewrap all comments at 72 chars.  In Goland, use the "Wrap to Column" plugin to make this effortless.
</blockquote></details>

Done.
___
*[`internal/conveyor/conveyor.go` line 45 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-NwpFxy3EVtR6SL2CcKc:-NwpqO1lDfB-bRxQHHaa:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/d7212dec15e869f2e99632032effd43a83297728/internal/conveyor/conveyor.go#L45)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

This type should be initialized via Wire, ideally making these fields private.  Since the kind must be configured by the user, it would make sense to have a `WithKind()` method that returns a shallow copy of the struct.
</blockquote></details>

Done.
___
*[`internal/conveyor/conveyor.go` line 141 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-NwpGZ5R-s-kR9J5uIgz:-NwpqRFl3dn9cVaBt2O1:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/d7212dec15e869f2e99632032effd43a83297728/internal/conveyor/conveyor.go#L141)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Sort order.
</blockquote></details>

Done.
___
*[`internal/conveyor/metrics.go` line 26 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-NwpGk2e6Ix2XrgKrMBG:-NwpqSxf0IlWhey_3Whh:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/d7212dec15e869f2e99632032effd43a83297728/internal/conveyor/metrics.go#L26)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

In the commit message, call this out as a breaking change.  I haven't seen anyone use a dashboard other than the one we ship, so this shouldn't be a big problem at the moment.
</blockquote></details>

Done.

**Review by bobvawter — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/842)* status: all files reviewed, 3 unresolved discussions (waiting on @BramGruneir and @sravotto)

___
*[`internal/source/cdc/resolved.go` line 72 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-NwpHNxJ9hhaOfiEWTBW:-NwpxhhuA3tC46hm-Qe5:bz2r1jm) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/d7212dec15e869f2e99632032effd43a83297728/internal/source/cdc/resolved.go#L72)):*
<details><summary><i>Previously, sravotto (silvano) wrote…</i></summary><blockquote>

So Advance expects an `Ident` (as a partition). I'm thinking that for cdc (as it is now) we are not really requiring anything. Can't we just pass an empty Ident, until we support multiple CDC feed per schema?
</blockquote></details>

That would break all existing installations, where the partition name equals the group name.
___
*[`internal/conveyor/conveyor.go` line 59 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-Nwpx7y_7M6sSo5uF4Zr:-Nwpx7y_7M6sSo5uF4Zs:bdxlwx1) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/fab4159fc8158ef478dfca632a2bbdc0a1dda98a/internal/conveyor/conveyor.go#L59)):*
> ```Go
> 
> // WithKind sets the kind of Conveyors, used in the exported metrics.
> func (c *Conveyors) WithKind(kind string) *Conveyors {
> ```

This should return a shallow copy.

```
ret := *c
ret.kind = kind
return &ret
```

Otherwise, it wouldn't be possible to (eventually) have multiple instances of the type within the same binary.

**Review by sravotto — COMMENTED** [review]
Please take another look. Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-:-NwuK9YH74R09ONwxgSN:b2xmk82)* status: 7 of 18 files reviewed, 3 unresolved discussions (waiting on @bobvawter and @BramGruneir)

___
*[`internal/source/cdc/resolved.go` line 72 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-NwpHNxJ9hhaOfiEWTBW:-NwuFkws17CJrzWLaC58:bag7c81) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/d7212dec15e869f2e99632032effd43a83297728/internal/source/cdc/resolved.go#L72)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

That would break all existing installations, where the partition name equals the group name.
</blockquote></details>

Done. We can fetch partition name directly from the Table Group for cdc.
___
*[`internal/conveyor/conveyor.go` line 59 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-Nwpx7y_7M6sSo5uF4Zr:-NwuFqf13UQoR1a88TB5:baq0z2u) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/fab4159fc8158ef478dfca632a2bbdc0a1dda98a/internal/conveyor/conveyor.go#L59)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

This should return a shallow copy.

```
ret := *c
ret.kind = kind
return &ret
```

Otherwise, it wouldn't be possible to (eventually) have multiple instances of the type within the same binary.
</blockquote></details>

As discussed, I created a clone method to create a shallow copy (without the underlying cache).

**Review by bobvawter — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/842#-:-NwuRcX99wSQwGNlbQTx:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BramGruneir)

**Pull request merged**
