### PR TITLE
Simple active-active demo.

### PR DESCRIPTION
**Pull request by sravotto**
The demo runs in a docker environment. It consists of 2 single node Cockroach clusters (named east and west), and 2 cdc-sink processes managing the replication flow (the processes are named east_west and west_east to indicate the direction of the replication each process is responsible for).

The README.md provides the details on how to set up the environment, the architecture and implementation notes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/665)

### CODE REVIEW

**Comment by daniel-crlabs** [comment]
I'm reviewing it

**Review by daniel-crlabs — COMMENTED** [review]
I was able to follow along without any major issues. I just encountered a slight problem when trying to start the containers, but this was most likely due to my small vms resources. I think we should add an additional interval and retries to the east and west services to account for folks who attempt to run this lab in less resourceful hardware, so the containers won't error out.

I was able to get around this by adding the following to the healthcheck of both east and west services:

```
interval: 5s
retries: 10
```

I also added ports to both services, just for my benefit, since I run these in a vm and can then access them from my laptop:

`east`

```
ports:
   - 30008:8080
   - 30007:26257
```

`west`

```
ports:
 - 30088:8080
 - 30077:26257
```

**Review by sravotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/665)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @bobvawter and @BramGruneir)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cdc-sink/665#-Nqii_ag8wC6dhCDMnuk:-Nqii_ag8wC6dhCDMnul:b-5dyko7) (no related file):*
@daniel-crlabs  Please take another look. I updated the health check to wait for longer. 
I decided to use dynamic ports, to avoid conflicts in a user environment. This will require an extra step for the user though, since they will have to run `docker compose port` to find out the local port.

___

**Review by bobvawter — APPROVED** [review]
> Reviewed 1 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/665)* status: 1 of 16 files reviewed, 4 unresolved discussions (waiting on @BramGruneir and @sravotto)

___
*[`scripts/active_active/README.md` line 15 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/665#-NsES2LtAqttosdu--I9:-NsES2LtAqttosdu--IA:b-gqvm0i) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/c05d2e02b80e5c82dd834a53aaad21232b8938de/scripts/active_active/README.md#L15)):*
> ```Markdown
> ## Configuration
> 
> You will need to set the `COCKROACH_DEV_LICENSE` and `COCKROACH_DEV_ORGANIZATION` environment variables.
> ```

The docker-compose could call `cockroach demo` which enables the enterprise features without the need for a license.
___
*[`scripts/active_active/userscripts/repl.ts` line 50 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/665#-NsET4Ph7eMv6J1Cjl1X:-NsET4Ph7eMv6J1Cjl1Y:bsd1wgn) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/c05d2e02b80e5c82dd834a53aaad21232b8938de/scripts/active_active/userscripts/repl.ts#L50)):*
> ```XML
>     api.configureTable(table, {
>         apply: async(ops: ApplyOp[]): Promise<any> => {
>             ops = ops.map((op: ApplyOp) => {
> ```

Why `map().filter()` and not just `filter()` ?
___
*[`scripts/active_active/userscripts/tsconfig.json` line 12 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/665#-NsETHI_DSVA0cgKsDql:-NsETHI_DSVA0cgKsDqm:b-7s8p82) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/c05d2e02b80e5c82dd834a53aaad21232b8938de/scripts/active_active/userscripts/tsconfig.json#L12)):*
> ```jsonc
>       "baseUrl": ".",
>       "paths": {
>           "cdc-sink@v1": ["../../../internal/script/testdata/cdc-sink@v1.d.ts"]
> ```

Something that might be nicer is to check a symlink into this directory that points to the `d.ts` file.

**Review by bobvawter — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/665)* status: 1 of 16 files reviewed, 5 unresolved discussions (waiting on @BramGruneir and @sravotto)

___
*[`scripts/active_active/userscripts/repl.ts` line 40 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/665#-NsEU6LV0q3xsVl6y5_H:-NsEU6LV0q3xsVl6y5_I:b-m1niz4) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/c05d2e02b80e5c82dd834a53aaad21232b8938de/scripts/active_active/userscripts/repl.ts#L40)):*
> ```XML
>  * @param tables - An array of table names.
>  */
> export function replicateTo(region: string, tables: string[]) {
> ```

Rename 'region' to 'target' for consistency.

**Review by sravotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/665)* status: 1 of 17 files reviewed, 5 unresolved discussions (waiting on @bobvawter and @BramGruneir)

___
*[`scripts/active_active/README.md` line 15 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/665#-NsES2LtAqttosdu--I9:-NsFirLgBn5bV9EmOa1_:b-y3ff0e) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/c05d2e02b80e5c82dd834a53aaad21232b8938de/scripts/active_active/README.md#L15)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

The docker-compose could call `cockroach demo` which enables the enterprise features without the need for a license.
</blockquote></details>

I'm not sure we can run `cockroach demo` inside a container?
___
*[`scripts/active_active/userscripts/repl.ts` line 40 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/665#-NsEU6LV0q3xsVl6y5_H:-NsFjEb5D9iyyZaKrRwh:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/c05d2e02b80e5c82dd834a53aaad21232b8938de/scripts/active_active/userscripts/repl.ts#L40)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Rename 'region' to 'target' for consistency.
</blockquote></details>

Done.
___
*[`scripts/active_active/userscripts/repl.ts` line 50 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/665#-NsET4Ph7eMv6J1Cjl1X:-NsFjFAVEEU_E7vYv6ZJ:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/c05d2e02b80e5c82dd834a53aaad21232b8938de/scripts/active_active/userscripts/repl.ts#L50)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Why `map().filter()` and not just `filter()` ?
</blockquote></details>

Done.
___
*[`scripts/active_active/userscripts/tsconfig.json` line 12 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/665#-NsETHI_DSVA0cgKsDql:-NsFjGnBBiu9WNGDvDwi:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/c05d2e02b80e5c82dd834a53aaad21232b8938de/scripts/active_active/userscripts/tsconfig.json#L12)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Something that might be nicer is to check a symlink into this directory that points to the `d.ts` file.
</blockquote></details>

Done.

**Pull request merged**
