### PR TITLE
cdc-sink: Add prometheus metrics

### PR DESCRIPTION
**Pull request by bobvawter**
This change adds wrappers around the core API defined in the types package to
provide a baseline set of metrics for operators. This approach was taken so as
to centralize the bulk of the metrics reporting in a single package, rather
than spreading it across the "target" subpackages.

The previously-existing logging wrapper in the server package is moved into
perf.

The retry package is also instrumented with counter metrics to report the
number of error codes. This will be useful in future hardening exercises.

Closes: #53

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/79)

### CODE REVIEW

**Review by BramGruneir — CHANGES_REQUESTED** [review]
I've never seen this approach at perf before.

I don't think I'm a fan of moving the logic into a wrapper in perf...  Perf is something that will always be present everywhere, as you can see here.  And this very much limits the perf to the larger functions call via the interface.  
And you even broke that with retry...

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/79#-:-MrYkXTBABWZPshmGjD8:bfyprnb)* status: all files reviewed, 2 unresolved discussions (waiting on @bobvawter and @sravotto)

___
*[internal/perf/http.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/79#-MrYmTz6CVF0gmBQQyyZ:-MrYmTz6CVF0gmBQQyy_:b-ipuvrq) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/136b1228e59a792118e32b6ae511e1c10539138c/internal/perf/http.go#L42)):*
> ```Go
> // HTTPHandler wraps the given handler with performance monitoring and
> // logging.
> func HTTPHandler(h http.Handler) http.Handler {
> ```

Ugh.  Not a fan of this at all.  

Now you've got the handler adding actual logging logic and shutdown logic into the perf package, it's not just a wrapper.
___
*[internal/target/apply/apply.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/79#-MrYmz_MBoq9eI2Q0nL_:-MrYmz_MBoq9eI2Q0nLa:bkybvha) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/136b1228e59a792118e32b6ae511e1c10539138c/internal/target/apply/apply.go#L63)):*
> ```Go
> 
> 	a := &apply{cancel: cancel, target: target}
> ```

Was this extra line intentional?

**Comment by bobvawter** [comment]
It's straightforward enough to break that `perf` package out into each of the leaf packages.  Will take those couple of ident-to-labels functions and drop them in a `util` sub-package.

**Comment by bobvawter** [comment]
PTAL. Reworked the metrics as spot changes throughout.  Also, find attached an example output of the `/_/varz` endpoint.

[demo.txt](https://github.com/cockroachdb/cdc-sink/files/7765836/demo.txt)

**Review by sravotto — COMMENTED** [review]
> Reviewed 16 of 19 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/79)* status: all files reviewed, 7 unresolved discussions (waiting on @bobvawter)

___
*[internal/source/server/metrics.go, line 21 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/79#-MrbiK8y246GHpb3yGgC:-MrbiK8y246GHpb3yGgD:b-lpv6r8) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/fdd6e46605080aaf56d80f372670adba8586272f/internal/source/server/metrics.go#L21)):*
> ```Go
> 	httpCodes = promauto.NewCounterVec(prometheus.CounterOpts{
> 		Name: "http_status_codes_total",
> 		Help: "the HTTP response latency",
> ```

Help should be "Counter for HTTP codes" or something like that
___
*[internal/source/server/metrics.go, line 23 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/79#-MrbjMPp6glpYoBvMFKs:-MrbjMPp6glpYoBvMFKt:b-gmu9vf) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/fdd6e46605080aaf56d80f372670adba8586272f/internal/source/server/metrics.go#L23)):*
> ```Go
> 		Help: "the HTTP response latency",
> 	}, []string{"code"})
> 	httpLatency = promauto.NewSummary(prometheus.SummaryOpts{
> ```

I prefer histograms to summaries.
We can use linear log10 buckets (with 10 bins for each log10), something like:
durationMillisBuckets = []float64{1,2,3,4,5,6,7,8,9,10,20,30,40,50,70,80,90,100,200,300,400,500,600,700,800,900,1000,2000,3000,4000,5000,6000,7000,8000,9000,10000}
___
*[internal/target/apply/metrics.go, line 28 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/79#-MrbkiCP3v-dtu0ireGU:-MrbkiCP3v-dtu0ireGV:b-z1fjbx) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/fdd6e46605080aaf56d80f372670adba8586272f/internal/target/apply/metrics.go#L28)):*
> ```Go
> 		Help:       "the length of time it took to successfully apply mutations",
> 		Objectives: metrics.Objectives,
> 	}, metrics.TableLabels)
> ```

Same as before, I would prefer histograms. 
___
*[internal/target/stage/metrics.go, line 42 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/79#-Mrbl_1AALUH3l3-42l7:-Mrbl_1AALUH3l3-42l8:b-89a4l7) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/fdd6e46605080aaf56d80f372670adba8586272f/internal/target/stage/metrics.go#L42)):*
> ```Go
> 		Help:       "the length of time it took to successfully store mutations",
> 		Objectives: metrics.Objectives,
> 	}, metrics.TableLabels)
> ```

Ditto
___
*[internal/target/timekeeper/metrics.go, line 24 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/79#-Mrblqo43rmgfQTA0Zpv:-Mrblqo43rmgfQTA0Zpw:b-89a4l7) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/fdd6e46605080aaf56d80f372670adba8586272f/internal/target/timekeeper/metrics.go#L24)):*
> ```Go
> 		Help:       "the length of time it took to successfully record resolved timestamps",
> 		Objectives: metrics.Objectives,
> 	})
> ```

Ditto

**Review by bobvawter — COMMENTED** [review]
The histograms are going to increase the total number of metrics in the system, since many of them are captured on a per-table basis.  If this becomes problematic in the field, we can add a flag to the metrics package to truncate the table/schema idents down to schema- or database-resolution.

> Dismissed @BramGruneir from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/79#-:-Mrc53zZ6h6HYNyyhm4F:b-f4boeu)* status: 17 of 24 files reviewed, 3 unresolved discussions (waiting on @BramGruneir and @sravotto)

___
*[internal/source/server/metrics.go, line 21 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/79#-MrbiK8y246GHpb3yGgC:-Mrc48IhEP84F7LAIulS:bt2vr1b) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/fdd6e46605080aaf56d80f372670adba8586272f/internal/source/server/metrics.go#L21)):*
<details><summary><i>Previously, sravotto (silvano) wrote…</i></summary><blockquote>

Help should be "Counter for HTTP codes" or something like that
</blockquote></details>

Fixed.
___
*[internal/source/server/metrics.go, line 23 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/79#-MrbjMPp6glpYoBvMFKs:-Mrc48zZAf2gNoJGPbVL:b2k1o0q) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/fdd6e46605080aaf56d80f372670adba8586272f/internal/source/server/metrics.go#L23)):*
<details><summary><i>Previously, sravotto (silvano) wrote…</i></summary><blockquote>

I prefer histograms to summaries.
We can use linear log10 buckets (with 10 bins for each log10), something like:
durationMillisBuckets = []float64{1,2,3,4,5,6,7,8,9,10,20,30,40,50,70,80,90,100,200,300,400,500,600,700,800,900,1000,2000,3000,4000,5000,6000,7000,8000,9000,10000}
</blockquote></details>

I switched all of the summaries over to histograms.  Added a utility function in the `utils/metrics` to compute the bucket values.  Also switched the `http_payload_in` metric to be a histogram from 1KiB up to 10MiB.
___
*[internal/target/apply/apply.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/79#-MrYmz_MBoq9eI2Q0nL_:-Mrc4c0m-vmvHZKj-2D2:bt2vr1b) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/136b1228e59a792118e32b6ae511e1c10539138c/internal/target/apply/apply.go#L63)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Was this extra line intentional?
</blockquote></details>

Fixed.

**Comment by bobvawter** [comment]
Some pretty pictures (running on my mac, which has poor fsync performance)

Screen Shot 2021-12-23 at 12 52 27

**Review by sravotto — COMMENTED** [review]
nice!
lgtm

> Reviewed 7 of 7 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/79#-:-MrcjBIX-UzOsIakFlpO:b-kbvppd)* status: all files reviewed, 1 unresolved discussion (waiting on @BramGruneir)

**Review by BramGruneir — APPROVED** [review]
:lgtm:

> Reviewed 3 of 19 files at r2, 1 of 3 files at r3, 7 of 7 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/79#-:-Msk7Kl0ErM-kTeKAiWY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bobvawter)

___
*[internal/target/stage/stage.go, line 42 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/79#-Msk1b8I32CJjDvKB0tj:-Msk1b8I32CJjDvKB0tk:b-lq37fh) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/0812d642fa029278f7523e72badedf2e96e4c5b9/internal/target/stage/stage.go#L42)):*
> ```Go
> 	stage ident.Table
> 
> 	drainCount    prometheus.Counter
> ```

Does it make sense to put these under a metric sub struct?  Not a needed change here, just a thought for the future.

**Pull request merged**
