### PR TITLE
docker and scripts restructure

### PR DESCRIPTION
**Pull request by glennfawcett**
Added `docker-compose.yml` with documentation and restructured the `scripts` directory.

- - -
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/537)

### CODE REVIEW

**Comment by glennfawcett** [comment]
merge when ready

**Comment by glennfawcett** [comment]
didn't mean to close

**Review by glennfawcett — COMMENTED** [review]
reviewed

**Review by glennfawcett — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/537)* status: 2 of 12 files reviewed, 5 unresolved discussions (waiting on @bobvawter)

___
*[`scripts/docker_c2c/docker-compose.yml` line 46 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/537#-NgsdX-jEQk8-KNVglhQ:-Nguam44C8tcfR9Yw2qG:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a1e3e2c15f04c95c2a4ccf454a2288eb2251b30b/scripts/docker_c2c/docker-compose.yml#L46)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Prefer the `:latest-v23.1` tag instead of a specific point release.
</blockquote></details>

Done.
___
*[`scripts/docker_c2c/docker-compose.yml` line 50 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/537#-Ngsck5O0PTDm7I8USAz:-Nguaqh7B43tUWRtxziu:begfetu) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a1e3e2c15f04c95c2a4ccf454a2288eb2251b30b/scripts/docker_c2c/docker-compose.yml#L50)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

There's a more elegant way to run a script in a container, which is to have `docker-compose` build an image.  We do this in `https://github.com/cockroachdb/cdc-sink/tree/master/.github/oracle-nne` which adds a configuration file.  Instead of using the `image:` property, you'd use the `build:` property with a relative path to the directory containing the Dockerfile: https://github.com/cockroachdb/cdc-sink/blob/master/.github/docker-compose.yml#L117

https://docs.docker.com/engine/reference/builder/#copy

Using this approach, you can write shell and/or sql scripts in a more typical approach:

```Dockerfile
FROM cockroachdb/cockroach:latest-v23.1
COPY my_script.sh some.sql other_files /usr/local/bin
ENTRYPOINT /usr/local/bin/my_script.sh
```

Your custom entrypoint can launch the cockroach process and perform the other setup steps.

The license and organization values can also become an `ARG` in the image: https://docs.docker.com/engine/reference/builder/#arg
</blockquote></details>

Going to leave it because it is more instructive on what is being done to bring up cdc-sink
___
*[`scripts/docker_c2c/docker-compose.yml` line 101 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/537#-NgsfNNC7RH5y8nq3QVy:-NgubEIj8LgBO7r5KWBh:b-jrb4vk) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a1e3e2c15f04c95c2a4ccf454a2288eb2251b30b/scripts/docker_c2c/docker-compose.yml#L101)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

The environment variable is called `COCKROACH_DEV_LICENSE` elsewhere; same for the organization one, too.
</blockquote></details>

Understood

**Review by glennfawcett — COMMENTED** [review]
Should be ready to commit and merge

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/537#-:-NgudOjl5AoiCFBzgUqE:b-8p0tqf)* status: 1 of 12 files reviewed, 5 unresolved discussions (waiting on @bobvawter)

___
*[`-- commits` line 8 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/537#-NgsbvN-3UmZmm9txA2n):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

The cdc-sink has branch protection that requires a linear history for the master branch.  There's also a merge queue that will handle rebasing your commits onto the tip immediately prior to committing.

In my workflow, when there are other changes that I actually need to pick up, I'll use the following recipe:

```sh
git fetch origin
git rebase -i origin/master
```

Then I'll rebase and/or squash commits onto the master branch.
</blockquote></details>

Ok.
___
*[`scripts/README.md` line 2 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/537#-NgscYFp5hDRqchtT1Fg:-NgucPxn40EVSs9BKuKq:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a1e3e2c15f04c95c2a4ccf454a2288eb2251b30b/scripts/README.md#L2)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Maybe explain what each of these demos would show?
</blockquote></details>

Done.

**Review by bobvawter — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/537)* status: 2 of 12 files reviewed, 7 unresolved discussions (waiting on @glennfawcett)

___
*[`-- commits` line 8 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/537#-NgsbvN-3UmZmm9txA2n):*
<details><summary><i>Previously, glennfawcett wrote…</i></summary><blockquote>

Ok.
</blockquote></details>

The PR still needs to be squashed.
___
*[`scripts/README.md` line 2 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/537#-NgscYFp5hDRqchtT1Fg:-Ngug0Mp0NLuII2-_-Sq:b-f3hbi8) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a1e3e2c15f04c95c2a4ccf454a2288eb2251b30b/scripts/README.md#L2)):*
<details><summary><i>Previously, glennfawcett wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I was thinking the description would be attached to each of the bullet points below.
___
*[`scripts/docker_c2c/docker-compose.yml` line 50 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/537#-Ngsck5O0PTDm7I8USAz:-NgueqsRAdJnztd3HAfE:b-tc6704) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a1e3e2c15f04c95c2a4ccf454a2288eb2251b30b/scripts/docker_c2c/docker-compose.yml#L50)):*
<details><summary><i>Previously, glennfawcett wrote…</i></summary><blockquote>

Going to leave it because it is more instructive on what is being done to bring up cdc-sink
</blockquote></details>

This docker-compose file isn't particularly readable, though, since the shell scripts are spread throughout a number of services and the control flow is indirect solely through dependencies.  It's taking a bit of effort to understand how it all fits together and I think that would tend to discourage the novice reader.  A single shell script running in a container would show the reader exactly what's going on, with no loss of generality from what's proposed here.
___
*[`scripts/docker_c2c/run_compose.sh` line 4 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/537#-NgugsWb1ehfq5RRjh4e:-NgugsWb1ehfq5RRjh4f:bpudu2k) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/ce521f4aa378f62bf3832b3d3bd514593b70fa75/scripts/docker_c2c/run_compose.sh#L4)):*
> ```Shell
> 
> #export LICENSE=""
> #export ORGANIZATION=""
> ```

Dangling comments?
___
*[`scripts/docker_c2c/run_compose.sh` line 8 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/537#-NgughaA9ARKtzGPEiSx:-NgughaA9ARKtzGPEiSy:bxarlz1) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/ce521f4aa378f62bf3832b3d3bd514593b70fa75/scripts/docker_c2c/run_compose.sh#L8)):*
> ```Shell
> if [ -z "$LICENSE" ] || [ -z "$ORGANIZATION" ]
> then
>      echo "The LICENSE and ORGANIZTION env variables must be set to run CRDB Changefeeds needed for cdc-sink"
> ```

Please rename as requested to maintain consistency in the cdc-sink repo.
___
*[`scripts/docker_c2c/run_compose.sh` line 18 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/537#-Nguh-KF3M17vkr5Xxwv:-Nguh-KF3M17vkr5Xxww:bnk9dgy) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/ce521f4aa378f62bf3832b3d3bd514593b70fa75/scripts/docker_c2c/run_compose.sh#L18)):*
> ```Shell
> export cid=`docker ps |grep grafana- |awk '{printf("%s",$1)}'`
> 
> echo "docker exec -it ${cid} /usr/share/grafana/bin/grafana cli --homepath /usr/share/grafana admin reset-admin-password cdc-sink"
> ```

This is also something that can be addressed by a local Dockerfile that patches the base grafana instance.

**Comment by bobvawter** [comment]
Pushed a commit to add copyright headers and revised the commit message slightly.

`go run github.com/google/addlicense -c "The Cockroach Authors" -l apache -s -v   -ignore '**/testdata/**/*.sql' .`

**Pull request merged**
