### PR TITLE
Add a Markdown Lint action

### PR DESCRIPTION
**Pull request by BramGruneir**
The defaults are quite sane, so I say we stick to them.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/186)

### CODE REVIEW

**Comment by BramGruneir** [comment]
Not sure if this will work and do its magic.

**Comment by BramGruneir** [comment]
Hmmm...  says no checks....  Any way to for it?

**Comment by BramGruneir** [comment]
So should I create a new action instead of adding to the current one?  

And I can define the action myself instead of using the marketplace's one, since it's not verified.

@bobvawter, what do you think is best here?

**Comment by bobvawter** [comment]
This should be in a new workflow file that fires when md files are changed.  See the `on` block at the top of `golang.yaml`.

You'll need to add that action to the allowed actions here: https://github.com/cockroachdb/cdc-sink/settings/actions

**Comment by BramGruneir** [comment]
@bobvawter, this is now working and ready for review.

**Review by bobvawter — APPROVED** [review]
:lgtm: w/ nits.

> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/186#-:-N7aS7MfAn_NyfJA6D9w:b-1ewmqt)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @bobvawter and @BramGruneir)

___
*[`.markdownlint.yaml` line 15 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/186#-N7aRxMF6pX-n7FOXch4:-N7aRxMF6pX-n7FOXch5:b-1cezvg) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/e675b2a3679467279cce92761f8237b26990981a/.markdownlint.yaml#L15)):*
> ```YAML
>   # Include headings
>   headings: true
>   # Include headings
> ```

`s/headings/headers/`

None of these "include X" comments really add to the discussion.
___
*[`.markdownlint.yaml` line 20 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/186#-N7aRBgo-u28R-1JJhdP:-N7aRBgo-u28R-1JJhdQ:bs7r5y3) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/e675b2a3679467279cce92761f8237b26990981a/.markdownlint.yaml#L20)):*
> ```YAML
>   strict: false
>   # Stern length checking
>   stern: false
> ```

Add a trailing newline.
___
*[`.github/workflows/linter.yaml` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/186#-N7aRGjs0jvsIfYuX5Ut:-N7aRGjs0jvsIfYuX5Uu:b-habgar) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/e675b2a3679467279cce92761f8237b26990981a/.github/workflows/linter.yaml#L1)):*
> ```YAML
> name: Linters
> ```

Call this workflow "Markdown" and rename the file.
___
*[`.github/workflows/linter.yaml` line 18 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/186#-N7aRQkzBhrpqvF1UZ3O:-N7aRQkzBhrpqvF1UZ3P:b-1lvhau) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/e675b2a3679467279cce92761f8237b26990981a/.github/workflows/linter.yaml#L18)):*
> ```YAML
>     steps:
>       - name: Checkout Code
>         uses: actions/checkout@v2
> ```

`v3` is the current version.
___
*[`scripts/demo_down.sh` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/186#-N7aReil2jgQ9rciDd1f:-N7aReil2jgQ9rciDd1g:b-ufn7b2) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/e675b2a3679467279cce92761f8237b26990981a/scripts/demo_down.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

Pedantic: `#!/usr/bin/env bash`

**Review by BramGruneir — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/186#-:-N7aZ1DOAzD5nO44GeD2:b-ucfknh)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @bobvawter)

___
*[`.markdownlint.yaml` line 15 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/186#-N7aRxMF6pX-n7FOXch4:-N7aVEQy1P61uDeqtQDP:b-p808e2) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/e675b2a3679467279cce92761f8237b26990981a/.markdownlint.yaml#L15)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

`s/headings/headers/`

None of these "include X" comments really add to the discussion.
</blockquote></details>

This was copied pasted from the markdown lint file directly.  But I agree, removed them.
___
*[`.markdownlint.yaml` line 20 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/186#-N7aRBgo-u28R-1JJhdP:-N7aVNAS2csWj68y7CNB:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/e675b2a3679467279cce92761f8237b26990981a/.markdownlint.yaml#L20)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Add a trailing newline.
</blockquote></details>

Done.
___
*[`scripts/demo_down.sh` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/186#-N7aReil2jgQ9rciDd1f:-N7aYm2y7iUYRHs-1NL-:b-s1s7cc) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/e675b2a3679467279cce92761f8237b26990981a/scripts/demo_down.sh#L1)):*
> #!/usr/bin/env bash
Done, and fixed the other one too.
___
*[`.github/workflows/linter.yaml` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/186#-N7aRGjs0jvsIfYuX5Ut:-N7aZKcT-bB39o2Qxe8s:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/e675b2a3679467279cce92761f8237b26990981a/.github/workflows/linter.yaml#L1)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Call this workflow "Markdown" and rename the file.
</blockquote></details>

Done.
___
*[`.github/workflows/linter.yaml` line 18 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/186#-N7aRQkzBhrpqvF1UZ3O:-N7aVdHRE2u06hxgqApd:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/e675b2a3679467279cce92761f8237b26990981a/.github/workflows/linter.yaml#L18)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

`v3` is the current version.
</blockquote></details>

Done.

**Pull request merged**
