### PR TITLE
mysql: integration tests

### PR DESCRIPTION
**Pull request by sravotto**
Adding integration for mysql.
As part of this commit, we changed the mysql driver, as we need support to set sql_mode on each session.

Includes the changes in #539

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/544)

### CODE REVIEW

**Review by sravotto — COMMENTED** [review]
Please take another look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/544#-:-Nh7YmELCR2UZCA93FGS:b1xog4q)* status: 20 of 35 files reviewed, 7 unresolved discussions (waiting on @bobvawter and @BramGruneir)

___
*[`go.mod` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/544#-Nh7JvBw6gJeeLbn1-pC:-Nh7WbI85PAPBJzzZjDa:b8swmmn) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/ee36cdbe0aee34d3eaea194013e989f8a246b703/go.mod#L56)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Could you run `go mod tidy`?  I'm surprised to see this dependency listed in the indirect section.
</blockquote></details>

I did run it, cleaned the go.sum, but left this as is...
___
*[`internal/target/apply/testdata/my/cas.upsert.sql` line 3 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/544#-Nh7HGQpDhYs96L0veRC:-Nh7V8Sr1W6LtOz8-Y_8:b-gefu8z) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/ee36cdbe0aee34d3eaea194013e989f8a246b703/internal/target/apply/testdata/my/cas.upsert.sql#L3)):*
first suggestion done.
However, I don't think I can use VALUES

```
> INSERT INTO aaa ("pk","ts","ver") with data ("pk","ts","ver") as (select 16,now(),2) select * from data;
Query OK, 1 row affected

> INSERT INTO aaa ("pk","ts","ver") with data ("pk","ts","ver") as (values (16,now(),2)) select * from data;
(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(16,now(),2)) select * from data' at line 1")
```
The second query works just fine in CRDB.
___
*[`internal/target/apply/testdata/my/cas.upsert.sql` line 19 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/544#-Nh7I-CwBuCbegOe-KR1:-Nh7WZ7o6DHPZqWwbByr:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/ee36cdbe0aee34d3eaea194013e989f8a246b703/internal/target/apply/testdata/my/cas.upsert.sql#L19)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Empty line in template output, probably just need a `{{- nl -}}` in the template somewhere to collapse the output.
</blockquote></details>

Done.
___
*[`internal/target/schemawatch/coldata.go` line 340 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/544#-Nh7I_qe2eChpy5lHwQg:-Nh7TNtRCOl95Mff8Cbh:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/ee36cdbe0aee34d3eaea194013e989f8a246b703/internal/target/schemawatch/coldata.go#L340)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Just for sanity's sake, also check that the string ends with a single-quote, too.
</blockquote></details>

Done.
___
*[`internal/target/schemawatch/coldata.go` line 343 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/544#-Nh7INOe-b67oiUy4ip1:-Nh7PHPKBrbNAXuo75vX:bj38rw5) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/ee36cdbe0aee34d3eaea194013e989f8a246b703/internal/target/schemawatch/coldata.go#L343)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Is there a test for a default value that contains a single-quote?  That is, does this code need to be able to escape anything?
</blockquote></details>

This is actually a change that I made while testing MariaDB. I decided to have more defensive code in general, just in case. I'll add a comment.
___
*[`internal/util/stdpool/my.go` line 44 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/544#-Nh7JBcHAP1Jx2BHpaKA:-Nh7TJB85eR8ihgFksw9:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/ee36cdbe0aee34d3eaea194013e989f8a246b703/internal/util/stdpool/my.go#L44)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Comment missing leading space.
</blockquote></details>

Done.
___
*[`internal/util/stdpool/my.go` line 94 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/544#-Nh7Jf9c39SPYIoUGKeY:-Nh7TJye0q78HsiqlrGa:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/ee36cdbe0aee34d3eaea194013e989f8a246b703/internal/util/stdpool/my.go#L94)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

I'm not sure what this error message is trying to say.
</blockquote></details>

Done.

**Review by bobvawter — CHANGES_REQUESTED** [review]
> Reviewed 7 of 35 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/544)* status: all files reviewed, 1 unresolved discussion (waiting on @BramGruneir and @sravotto)

___
*[`internal/target/schemawatch/coldata.go` line 343 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/544#-Nh7INOe-b67oiUy4ip1:-Nh7axey4MkBh-7ElWF2:b3c08up) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/ee36cdbe0aee34d3eaea194013e989f8a246b703/internal/target/schemawatch/coldata.go#L343)):*
<details><summary><i>Previously, sravotto (silvano) wrote…</i></summary><blockquote>

This is actually a change that I made while testing MariaDB. I decided to have more defensive code in general, just in case. I'll add a comment.
</blockquote></details>

If you're wrapping arbitrary text in quotes, though, you need to escape any occurrence of the quote character within the string before sending it back to the database.

**Review by sravotto — COMMENTED** [review]
Done - added few tests to verify as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/544#-:-Nh8LQIvD_aqpkoH1T4c:btcmi9z)* status: 34 of 37 files reviewed, 1 unresolved discussion (waiting on @bobvawter and @BramGruneir)

___
*[`internal/target/schemawatch/coldata.go` line 343 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/544#-Nh7INOe-b67oiUy4ip1:-Nh8LN556ZvgDGcMdyIE:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/ee36cdbe0aee34d3eaea194013e989f8a246b703/internal/target/schemawatch/coldata.go#L343)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

If you're wrapping arbitrary text in quotes, though, you need to escape any occurrence of the quote character within the string before sending it back to the database.
</blockquote></details>

Done.

**Review by bobvawter — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/544#-:-Nh8SDK79haODQGQCG2j:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @BramGruneir)

**Comment by BramGruneir** [comment]
🏆 !

**Pull request merged**
