### PR TITLE
staging/checkpoint: Add checkpoint timestamp manager

### PR DESCRIPTION
**Pull request by bobvawter**
This PR is stacked on #674, #675, and #677. The relevant changes are in the tail commit.

- - -
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/679)

### CODE REVIEW

**Review by sravotto — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/679)* status: 8 of 16 files reviewed, 1 unresolved discussion (waiting on @bobvawter and @BramGruneir)

___
*[`-- commits` line 39 at r6](https://reviewable.io/reviews/cockroachdb/cdc-sink/679#-Nq5Gx5f4wW0q6JJFrrO):*
Code looks good to me. However, I would suggest to change the name. Group doesn't mean anything to me.
Maybe a CheckpointLog/TimestampLog where timestamp are Advanced and Resolved (rather than Marked/Recorded).
Thoughts on adding this to types as an interface?

**Review by BramGruneir — APPROVED** [review]
So... want to just rename this checkpoint now?  Since that's what resolved timestamps are for per Sean's comments?  Or perhaps just rename the table itself.

:lgtm: 

> Reviewed 9 of 9 files at r6, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/679#-:-Nq4b0Ax5yxw51NEqzFo:b1keovj)* status: all files reviewed, 5 unresolved discussions (waiting on @bobvawter)

___
*[`internal/staging/resolved/group.go` line 46 at r7](https://reviewable.io/reviews/cockroachdb/cdc-sink/679#-Nq8bPalAT7YV6jYWV5o:-Nq8bPalAT7YV6jYWV5p:b-dw7pwx) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a036ef3b1adeea80b201c7c6a60f54dca3c2768e/internal/staging/resolved/group.go#L46)):*
> ```Go
>   target_applied_at TIMESTAMPTZ,
>   source_wall_time  TIMESTAMPTZ AS (to_timestamp(source_nanos::FLOAT8 / 1e9)) VIRTUAL,
>   PRIMARY KEY (target_schema, source_nanos, source_logical),
> ```

Please add a now column that's populated on insert to help with tracking performance.
___
*[`internal/staging/resolved/group.go` line 57 at r7](https://reviewable.io/reviews/cockroachdb/cdc-sink/679#-Nq8bUQi1n7BZvghmpoE:-Nq8bUQi1n7BZvghmpoF:b-dw7pwx) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a036ef3b1adeea80b201c7c6a60f54dca3c2768e/internal/staging/resolved/group.go#L57)):*
> ```Go
>   source_logical    INT     NOT NULL,
>   target_applied_at TIMESTAMPTZ,
>   PRIMARY KEY (target_schema, source_nanos, source_logical),
> ```

Please add a now column that's populated on insert to help with tracking performance.
___
*[`internal/staging/resolved/group.go` line 76 at r7](https://reviewable.io/reviews/cockroachdb/cdc-sink/679#-Nq8blL_6hEGR-uOEJ70:-Nq8blL_6hEGR-uOEJ71:b-4c7gfx) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a036ef3b1adeea80b201c7c6a60f54dca3c2768e/internal/staging/resolved/group.go#L76)):*
> ```Go
> 		committedTime   prometheus.Gauge
> 		markDuration    prometheus.Observer
> 		proposedAge     prometheus.Gauge
> ```

`processsDuration`, `processing` and `flushDuration` have been removed.  Just making sure this was intentional.
___
*[`internal/staging/resolved/provider.go` line 39 at r7](https://reviewable.io/reviews/cockroachdb/cdc-sink/679#-Nq998qW9ap8X9bUpL7H:-Nq998qW9ap8X9bUpL7I:b-qa4qyg) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a036ef3b1adeea80b201c7c6a60f54dca3c2768e/internal/staging/resolved/provider.go#L39)):*
> ```Go
> 	metaTable := ident.NewTable(meta.Schema(), ident.New("resolved_timestamps"))
> 	ddl := schema
> 	if strings.Contains(pool.Version, "v21.") || strings.Contains(pool.Version, "v22.1.") {
> ```

Do we do this often?  Maybe we should create a separate package just for getting the cockroach version.  Perhaps have a common interface that we could add to all our source and target dbs. 

(not for now of course, just a thought)
___
*[`internal/types/table_group.go` line 35 at r7](https://reviewable.io/reviews/cockroachdb/cdc-sink/679#-Nq9EJnpDSEwzyrWLSe3:-Nq9EJnqE7waAtZNiWrt:b-iazsdg) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a036ef3b1adeea80b201c7c6a60f54dca3c2768e/internal/types/table_group.go#L35)):*
> ```Go
> 	// Optional. If present, this field indicates that the group
> 	// comprises the entire schema, implying known and unknown tables.
> 	Enclosing ident.Schema
> ```

Why does this matter now?  I'm assuming this is from work you've done in further PRs.

**Review by bobvawter — COMMENTED** [review]
I'm going to rename the package and other API bits to `checkpoints`, but leave the `resolved_timestamp` table name in place.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/679#-:-Nq9RRjn1jOOvemhXnoU:b1eioxm)* status: all files reviewed, 5 unresolved discussions (waiting on @BramGruneir)

___
*[`internal/staging/resolved/group.go` line 46 at r7](https://reviewable.io/reviews/cockroachdb/cdc-sink/679#-Nq8bPalAT7YV6jYWV5o:-Nq9R9VO6dWYnTVsYyhi:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a036ef3b1adeea80b201c7c6a60f54dca3c2768e/internal/staging/resolved/group.go#L46)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Please add a now column that's populated on insert to help with tracking performance.
</blockquote></details>

Done.
___
*[`internal/staging/resolved/group.go` line 57 at r7](https://reviewable.io/reviews/cockroachdb/cdc-sink/679#-Nq8bUQi1n7BZvghmpoE:-Nq9R9l137oNo5r2InKX:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a036ef3b1adeea80b201c7c6a60f54dca3c2768e/internal/staging/resolved/group.go#L57)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Please add a now column that's populated on insert to help with tracking performance.
</blockquote></details>

Done.
___
*[`internal/staging/resolved/group.go` line 76 at r7](https://reviewable.io/reviews/cockroachdb/cdc-sink/679#-Nq8blL_6hEGR-uOEJ70:-Nq9RAaj4sndFgLljvnD:b-vkrls3) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a036ef3b1adeea80b201c7c6a60f54dca3c2768e/internal/staging/resolved/group.go#L76)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

`processsDuration`, `processing` and `flushDuration` have been removed.  Just making sure this was intentional.
</blockquote></details>

It is, there are analogous metrics in the sequencers package. The resolved helper is no longer responsible for dispatching work.
___
*[`internal/types/table_group.go` line 35 at r7](https://reviewable.io/reviews/cockroachdb/cdc-sink/679#-Nq9EJnpDSEwzyrWLSe3:-Nq9RNiL7eouhimhs51h:b-g4hqqk) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/a036ef3b1adeea80b201c7c6a60f54dca3c2768e/internal/types/table_group.go#L35)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why does this matter now?  I'm assuming this is from work you've done in further PRs.
</blockquote></details>

Yes, it's used in a future commit.

**Review by sravotto — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/679#-:-Nq9v0SbC4ps1nAd8RKc:b-1m4vin)* status: 8 of 17 files reviewed, 5 unresolved discussions (waiting on @bobvawter and @BramGruneir)

**Pull request merged**
