### PR TITLE
apply: Implement compare-and-set, deadlines

### PR DESCRIPTION
**Pull request by bobvawter**
Note to reviewers: this PR is based on PR #85 (adding the request type).

This change adds the ability to use certain columns in the target table for
compare-and-set operations. That is, staged mutations will only be applied if
the proposed data has a CAS tuple that is strictly greater than the CAS tuple
of the data currently in the target table.

Additionally, certain columns can be used to impose deadlines on the
application of certain mutations.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/86)

### CODE REVIEW

**Comment by bobvawter** [comment]
I'm open to changing up how the feed configuration is performed.  It feels a little bit forced to drive all of this through query parameters.  Maybe in a follow-on, all of this configuration lives in the destination database, and is stored in the `_cdc_sink` db?  We could have a utility method in the binary to set the configuration on a per-destination-schema basis.

**Comment by bobvawter** [comment]
Added a benchmark to the PR to compare the different strategies. Numbers below are from my Mac running 21.2.4, two parallel workers, and 10s benchtime.


Using an in-memory store, the CAS operation is slower, as we'd expect for having to do a read-modify-write cycle.  In absolute terms, the difference isn't so bad.

```
BenchmarkApply/base-2         	   92144	    128949 ns/op
BenchmarkApply/cas-2          	   33788	    372027 ns/op
BenchmarkApply/deadline-2     	   77379	    155611 ns/op
BenchmarkApply/cas+deadline-2 	   31888	    388598 ns/op
```

With an on-disk store, we see that the disk latency dominates and the relative speed is equivalent.  The fsync on my laptop's storage is pretty awful; the average time lines up with the log-commit latency timeseries.

```
BenchmarkApply/base-2         	     387	  26827872 ns/op
BenchmarkApply/cas-2          	     409	  26391692 ns/op
BenchmarkApply/deadline-2     	     406	  25822864 ns/op
BenchmarkApply/cas+deadline-2 	     432	  26482002 ns/op
```

**Comment by BramGruneir** [comment]
I really like the idea of moving the configuration into the destination database... I didn't think about that before.  We could validate the config upon startup.  It would allow for much more readable configurations and we could use the current syntax to write/compare with what is written there.  

Need to think about this more, but I think pulling on that thread would be interesting.

**Review by BramGruneir — APPROVED** [review]
:lgtm:

The generated sql seems correct.  But it's not that easy to check, so it has to rely on the tests.

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/86#-:-MurVDYf9kWDnbVeyjXU:b-rfi062)* status: all files reviewed, 7 unresolved discussions (waiting on @bobvawter and @sravotto)

___
*[README.md, line 250 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/86#-MurCYWh2AOou66UNi8P:-MurCYWh2AOou66UNi8Q:b-w6sa55) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/e490667f459ca887e16ad5b097ae59729351ff06/README.md#L250)):*
> ```Markdown
> All tables in the feed must have all named `cas` columns or the changefeed will fail.
> 
> Deletes from the source cluster are always applied.
> ```

Please add examples here for all of these different operation methods.  When it would discard and etc.

Also, you should describe the default operation as well.

And what, you can mix and match.
___
*[internal/target/apply/apply.go, line 292 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/86#-MurE0e59x0RQuIYwAoN:-MurE0e59x0RQuIYwAoO:b-s14gdo) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/e490667f459ca887e16ad5b097ae59729351ff06/internal/target/apply/apply.go#L292)):*
> ```Go
> 	}
> 
> 	a.upserts.Add(float64(rowsUpserted))
> ```

Why not put this line directly in the loop instead of keeping here?  Is this operation slower?
___
*[internal/target/apply/apply.go, line 302 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/86#-MurES4p69vEbnR05lvN:-MurES4p69vEbnR05lvO:bu2zs1a) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/e490667f459ca887e16ad5b097ae59729351ff06/internal/target/apply/apply.go#L302)):*
> ```Go
> // refreshUnlocked updates the apply with new column information.
> func (a *apply) refreshUnlocked(colData []types.ColData) error {
> 	// We want to verify that the cas columns actually exist in the
> ```

cas and deadline columns
___
*[internal/target/apply/apply.go, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/86#-MurEc6dECF9XsAU6jRO:-MurEc6dECF9XsAU6jRP:b-ccj5pp) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/e490667f459ca887e16ad5b097ae59729351ff06/internal/target/apply/apply.go#L308)):*
> ```Go
> 		allColNames[col.Name] = struct{}{}
> 	}
> 	for _, col := range a.casColumns {
> ```

Perhaps we should store the column names in a map instead of an array?

Then you would only need to loop once right?  No need to loop the columns into a map, then again go through each array of column names.
___
*[internal/target/apply/apply_test.go, line 567 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/86#-MurSRqT8RJg5_AfFHQB:-MurSRqU1y_DFMwLyYjv:bjhup6) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/e490667f459ca887e16ad5b097ae59729351ff06/internal/target/apply/apply_test.go#L567)):*
> ```Go
> }
> 
> func BenchmarkApply(b *testing.B) {
> ```

I love the benchmarks!
___
*[internal/target/apply/apply_test.go, line 568 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/86#-MurUUuHD7b2mugKn8st:-MurUUuHD7b2mugKn8su:b44pxs5) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/e490667f459ca887e16ad5b097ae59729351ff06/internal/target/apply/apply_test.go#L568)):*
> ```Go
> 
> func BenchmarkApply(b *testing.B) {
> 	b.Run("base", func(b *testing.B) { benchConditions(b, false, false) })
> ```

There will be other options, perhaps make this a struct instead of just two bools.
___
*[internal/target/apply/templates.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/86#-MurHagg05x33LGyYXMG:-MurHagg05x33LGyYXMH:blawtck) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/e490667f459ca887e16ad5b097ae59729351ff06/internal/target/apply/templates.go#L37)):*
> ```Go
> 
> 		// qualify is used with the "join" template to emit a list
> 		// of qualified database identifiers.
> ```

Please add an example here of what the format is.

**Review by bobvawter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/86)* status: all files reviewed, 7 unresolved discussions (waiting on @BramGruneir and @sravotto)

___
*[README.md, line 250 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/86#-MurCYWh2AOou66UNi8P:-MuunlIe0GlHt8oU4SRA:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/e490667f459ca887e16ad5b097ae59729351ff06/README.md#L250)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Please add examples here for all of these different operation methods.  When it would discard and etc.

Also, you should describe the default operation as well.

And what, you can mix and match.
</blockquote></details>

Done.
___
*[internal/target/apply/apply.go, line 292 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/86#-MurE0e59x0RQuIYwAoN:-Muuk203ElBI-7N-FFsX:b-p5rphl) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/e490667f459ca887e16ad5b097ae59729351ff06/internal/target/apply/apply.go#L292)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why not put this line directly in the loop instead of keeping here?  Is this operation slower?
</blockquote></details>

I want to defer the metric update until we know that the batch of operations has succeeded in its entirety.  Added a comment.
___
*[internal/target/apply/apply.go, line 302 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/86#-MurES4p69vEbnR05lvN:-MuugDCECY5r3TqNH65x:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/e490667f459ca887e16ad5b097ae59729351ff06/internal/target/apply/apply.go#L302)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

cas and deadline columns
</blockquote></details>

Done.
___
*[internal/target/apply/apply.go, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/86#-MurEc6dECF9XsAU6jRO:-MuugisA8UBiKjsGdig6:b5eonqa) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/e490667f459ca887e16ad5b097ae59729351ff06/internal/target/apply/apply.go#L308)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Perhaps we should store the column names in a map instead of an array?

Then you would only need to loop once right?  No need to loop the columns into a map, then again go through each array of column names.
</blockquote></details>

I'm validating that the new columns in `colData` contain all ident referenced by the user-configured `casColumns` and `deadlines` fields in the `apply` struct.  I'd still need to loop over both `casColumns` and `deadlines`, regardless of how they're stored.  I suppose that the schema-watcher API could be changed to return a `map[ident.Ident]types.ColData` instead of `[]types.ColData`, but that seems invasive for code that is executed once and startup and then only again if there's a schema change.
___
*[internal/target/apply/apply_test.go, line 567 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/86#-MurSRqT8RJg5_AfFHQB:-MuuhXKIC777cy4S_6B0:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/e490667f459ca887e16ad5b097ae59729351ff06/internal/target/apply/apply_test.go#L567)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

I love the benchmarks!
</blockquote></details>

Done.
___
*[internal/target/apply/apply_test.go, line 568 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/86#-MurUUuHD7b2mugKn8st:-MuuiFi6-rfk5e0wz3Y5:b-fzjsaa) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/e490667f459ca887e16ad5b097ae59729351ff06/internal/target/apply/apply_test.go#L568)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

There will be other options, perhaps make this a struct instead of just two bools.
</blockquote></details>

Done.  Made `BenchmarkApply()` look more like a data-driven test with a new `benchConfig` type.
___
*[internal/target/apply/templates.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/86#-MurHagg05x33LGyYXMG:-Muuj9jGAD_HA38llwQh:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/e490667f459ca887e16ad5b097ae59729351ff06/internal/target/apply/templates.go#L37)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Please add an example here of what the format is.
</blockquote></details>

Done.

**Pull request merged**
