### PR TITLE
cdc-sink: Add structured logging

### PR DESCRIPTION
**Pull request by bobvawter**
This commit adds the logrus structured logging package. It is chosen because it
is mature and has a large ecosystem of formatters and hooks to support easy
integration with centralized logging services. The logrus API provides a way to
respond gracefully to fatal errors by registering callbacks when a fatal
message or log.Exit() are called.

Users have the option for a friendly, colorized output or a json format that is
compatible with fluent and StackDriver. There is also an option to write the
logs to a file, instead of stdout.

Compatibility with fluentd and StackDriver is provided via the
logrus-recommended joonix/log package.

See: https://github.com/sirupsen/logrus/wiki/Hooks
Closes: #41
Closes: #59

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/76)

### CODE REVIEW

**Comment by bobvawter** [comment]
@fabiog1901 please advise if your use case needs additional logging configuration.

An example, prettified, log message from the http endpoint:

```json
{
  "httpRequest": {
    "requestMethod": "PUT",
    "requestUrl": "/_test_db_2052/public/2021-12-21/202112212253039192656270000000001-823bcd69ebe2948c-1-2-00000001-_test_table_9930-1.ndjson",
    "requestSize": "92",
    "status": 200,
    "responseSize": "3",
    "userAgent": "Go-http-client/1.1",
    "latency": {
      "nanos": 2605985
    }
  },
  "severity": "INFO",
  "timestamp": {
    "seconds": 1640127189,
    "nanos": 188458870
  }
}
```

The pretty console output looks like:

```
% ./cdc-sink --version
INFO   [Dec 21 17:56:49] cdc-sink                                      arch=arm64 build="<unknown>" os=darwin runtime=go1.17.3
INFO   [Dec 21 17:56:49] github.com/golang/protobuf                    sum="h1:YF8+flBXS5eO826T4nzqPrxfhQThhXl0YzfuUPu4SBg=" version=v1.3.1
INFO   [Dec 21 17:56:49] github.com/jackc/chunkreader/v2               sum="h1:i+RDz65UE+mmpjTfyz0MoVTnzeYxroil2G82ki7MGG8=" version=v2.0.1
INFO   [Dec 21 17:56:49] github.com/jackc/pgconn                       sum="h1:DzdIHIjG1AxGwoEEqS+mGsURyjt4enSmqzACXvVzOT8=" version=v1.10.1
INFO   [Dec 21 17:56:49] github.com/jackc/pgio                         sum="h1:g12B9UwVnzGhueNavwioyEEpAmqMe1E/BN9ES+8ovkE=" version=v1.0.0
INFO   [Dec 21 17:56:49] github.com/jackc/pgpassfile                   sum="h1:/6Hmqy13Ss2zCq62VdNG8tM1wchn8zjSGOBJ6icpsIM=" version=v1.0.0
INFO   [Dec 21 17:56:49] github.com/jackc/pgproto3/v2                  sum="h1:r7JypeP2D3onoQTCxWdTpCtJ4D+qpKr0TxvoyMhZ5ns=" version=v2.2.0
INFO   [Dec 21 17:56:49] github.com/jackc/pgservicefile                sum="h1:C8S2+VttkHFdOOCXJe+YGfa4vHYwlt4Zx+IVXQ97jYg=" version=v0.0.0-20200714003250-2b9c44734f2b
INFO   [Dec 21 17:56:49] github.com/jackc/pgtype                       sum="h1:MJc2s0MFS8C3ok1wQTdQxWuXQcB6+HwAm5x1CzW7mf0=" version=v1.9.1
INFO   [Dec 21 17:56:49] github.com/jackc/pgx/v4                       sum="h1:71oo1KAGI6mXhLiTMn6iDFcp3e7+zon/capWjl2OEFU=" version=v4.14.1
INFO   [Dec 21 17:56:49] github.com/jackc/puddle                       sum="h1:gI8os0wpRXFd4FiAY2dWiqRK037tjj3t7rKFeO4X5iw=" version=v1.2.1
INFO   [Dec 21 17:56:49] github.com/joonix/log                         sum="h1:k+SfYbN66Ev/GDVq39wYOXVW5RNd5kzzairbCe9dK5Q=" version=v0.0.0-20200409080653-9c1d2ceb5f1d
INFO   [Dec 21 17:56:49] github.com/pkg/errors                         sum="h1:FEBLx1zS214owpjy7qsBeixbURkuhQAwrK5UwLGTwt4=" version=v0.9.1
INFO   [Dec 21 17:56:49] github.com/sirupsen/logrus                    sum="h1:dJKuHgqk1NNQlqoA6BTlM1Wf9DOH3NBjQyu0h9+AZZE=" version=v1.8.1
INFO   [Dec 21 17:56:49] golang.org/x/crypto                           sum="h1:0es+/5331RGQPcXlMfP+WrnIIS6dNnNRe0WB02W0F4M=" version=v0.0.0-20211215153901-e495a2d5b3d3
INFO   [Dec 21 17:56:49] golang.org/x/net                              sum="h1:hEYJvxw1lSnWIl8X9ofsYMklzaDs90JI2az5YMd4fPM=" version=v0.0.0-20211216030914-fe4d6282115f
INFO   [Dec 21 17:56:49] golang.org/x/sys                              sum="h1:fLOSk5Q00efkSvAm+4xcoXD+RRmLmmulPn5I3Y9F2EM=" version=v0.0.0-20211216021012-1d35b9e2eb4e
INFO   [Dec 21 17:56:49] golang.org/x/text                             sum="h1:olpwvP2KacW1ZWvsR7uQhoyTYvKAupfQrRGBFM352Gk=" version=v0.3.7
INFO   [Dec 21 17:56:49] google.golang.org/genproto                    sum="h1:4rNOqY4ULrKzS6twXa619uQgI7h9PaVd4ZhjFQ7C5zs=" version=v0.0.0-20190522204451-c2c4e71fbf69
```

**Comment by fabiog1901** [comment]
Safe to close, thank you


Best,
Fabio


Fabio Ghirardello | Enterprise Architect
***@***.***
(516) 424-8217

**Review by sravotto — COMMENTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/76)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @BramGruneir)

**Review by bobvawter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/76)* status: all files reviewed, 1 unresolved discussion (waiting on @BramGruneir)

___
*[internal/source/server/wrapper.go, line 90 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/76#-MrYjKzt7HtI5XZvaBry:-MrYjwtL0rRfbYtUYefN:b-6h4erd) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/32afa8f68274d50ee1feeb97b5c15afd066fd43f/internal/source/server/wrapper.go#L90)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Fatal?  I'm assuming this is just how joonix suggests to handle all of this?
</blockquote></details>

The use of `logrus.Fatal()`, by way of the message object, will trigger the shutdown hooks that are registered in a handful of calls to `log.DeferExitHandler()`.  I've verified that the http server will drain gracefully and then the process terminates.

**Pull request merged**
