### PR TITLE
core: Unify sequencer behaviors and channelize staging reads

### PR DESCRIPTION
**Pull request by bobvawter**
This change replaces the staging query API and collapses the besteffort,
serial, and shingle sequencers into a single implementation. The motivation for
making this change is to allow the reads from the staging tables to take place
concurrently with applying changes. A single sequencer implementation also
reduces the total number of distinct code paths; the previous behaviors are now
a matter of setup and configuration of the core sequencer.

The Stagers.Read method now returns a channel of StagingCursor values. This
"channels of cursors" pattern is repeated in lower layers of the staging reader
code. At the bottom is a tableReader, which is responsible for querying
sequential values from a single table. The outputs of multiple tableReaders are
consumed, incrementally, by a tableMerger. The tableMerge performs an
application-side, time-ordered join over the tableCursor channels to produce
the StagingCursor results. Performing the join in the application outperforms
performing the join in the database and allows us better control of pagination.
The complex SQL generation has been removed in favor of a basic key-based
pagination query in tableReader.

A new sequtil.Copier type consumes the StagingCursors to aggregate the
time-joined data into reasonably-sized batches of data to apply to the target
database. Copier uses an event-style callback API to provide batches of data to
flush and to report on the overall progress across the underlying tables.

The Core sequencer is driven by the Copier to schedule tasks that apply the
batches of data to the target. This uses the existing lockset and scheduler
code to prevent two batches that operate on the same row from executing
concurrently. The Core sequencer also communicates the Copier's progress to the
progress notify.Var that collaborates with the chepointpoint package.
Internally, asynchronous progress notifications are kept ordered by using a
channel-of-channels approach. The poisoned-key tracking code is hoisted from
the besteffort package into a poisonSet helper. The original serial.acceptor
code is copied unchanged into the core package.

The BestEffort sequencer is now a sequencer shim that starts multiple instances
of its delegate Sequencer (i.e. Core) over independent tables and reports on
the progress made. It no longer performs any sweeping over the staging tables.

The chaos sequencer shim now randomly sleeps for up to 1ms to encourage
goroutine scheduling jitter.

Progress reporting is now via hlc.Range instead of hlc.Time. This avoids any
confusion about whether or not any given timestamp would have been inclusive or
exclusive of the timestamps actually processed. This is also an API hedge
against possibly operating over non-contiguous or otherwise-bounded timestamps
in a future iteration of the product.

Additional metrics and points of configuration have been added throughout. Most
notably, there is now a "cdc_target_source_lag_seconds" value which reports on
the last observed resolved timestamp.

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/767)

### CODE REVIEW

**Comment by bobvawter** [comment]
Test flakes are due to https://github.com/go-sql-driver/mysql/issues/1559

**Comment by bobvawter** [comment]
Picked up a fix from the mysql driver maintainer.

**Review by BramGruneir — APPROVED** [review]
:lgtm:

Just some minor comments.  I'm sure I missed stuff, but I tried to go through your logic everywhere.

> Reviewed 71 of 71 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-:-NtNGHCT1P_p57kMCa_r:bmdqg3f)* status: all files reviewed, 15 unresolved discussions (waiting on @bobvawter and @sravotto)

___
*[`internal/sequencer/sequencer.go` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-Nt2xQJp0TxZpVQNhCSJ:-Nt2xQJqE-6PNGp3TRuI:b9i9gt9) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/5f61e92a8f74f43577828e8081e7b3fd4c837586/internal/sequencer/sequencer.go#L88)):*
> ```Go
> }
> 
> // CommonProgress is a returns the minimum progress across all tables
> ```

language
___
*[`internal/sequencer/core/core.go` line 279 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-NtHG0pN9SPZzHuITOql:-NtHG0pN9SPZzHuITOqm:bt2o3ji) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/17c22d7bd19655459be05324c90ba03d3c8f7d39/internal/sequencer/core/core.go#L279)):*
> ```Go
> 		toMonitor := []lockset.Outcome{copyOutcome}
> 		for {
> 			// Filer successes or exit on errors.
> ```

Filer?
___
*[`internal/sequencer/core/poison.go` line 109 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-NtHMbexC5GlmJNkupMf:-NtHMbexC5GlmJNkupMg:b-8fckvi) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/17c22d7bd19655459be05324c90ba03d3c8f7d39/internal/sequencer/core/poison.go#L109)):*
> ```Go
> 
> // isPoisoned returns a set of keys to contaminate.
> func (p *poisonSet) isPoisoned(batch *types.MultiBatch) (map[poisonedKey]struct{}, bool) {
> ```

This seems to be named really poorly.  It returns if there are new uncontaminated keys that should be contaminated and if there was anything poisoned,
___
*[`internal/sequencer/core/poison.go` line 136 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-NtHusYv2FGDwq9GNpuJ:-NtHusYv2FGDwq9GNpuK:b-nky0iw) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/17c22d7bd19655459be05324c90ba03d3c8f7d39/internal/sequencer/core/poison.go#L136)):*
> ```Go
> 		return nil
> 	}))
> 	return toContaminate, isPoisoned
> ```

If isPoisoned is false... do we still want to send back this toContaminate batch?
___
*[`internal/sequencer/core/round.go` line 97 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-NtHyeA_5ilYfECciAHs:-NtHyeA_5ilYfECciAHt:b-o2ep6m) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/17c22d7bd19655459be05324c90ba03d3c8f7d39/internal/sequencer/core/round.go#L97)):*
> ```Go
> 		// has a side effect of contaminating all keys in the batch to
> 		// ensure correct dependencies.
> 		if r.poisoned.IsPoisoned(r.batch) {
> ```

Spread?  Contaminate?  IsPoisoned isn't clear that it will cause the contamination to spread.
___
*[`internal/sequencer/core/round.go` line 164 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-NtHzfl2AmAh6r1onOIN:-NtHzfl2AmAh6r1onOIO:b-ojljfb) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/17c22d7bd19655459be05324c90ba03d3c8f7d39/internal/sequencer/core/round.go#L164)):*
> ```Go
> 	// Close out the transaction, unless we expect
> 	// additional data in the next callback.
> 	err = errors.WithStack(targetTx.Commit())
> ```

Does this close it?  I don't see the other path unless the Commit itself doesn't always try to commit.
___
*[`internal/sequencer/core/round.go` line 169 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-NtI-M7EEPBiXW0YySlf:-NtI-M7EEPBiXW0YySlg:b7uk9iv) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/17c22d7bd19655459be05324c90ba03d3c8f7d39/internal/sequencer/core/round.go#L169)):*
> ```Go
> 	}
> 
> 	stagingTx, err := r.stagingPool.BeginTx(ctx, pgx.TxOptions{})
> ```

Does it make sense to channel these to a different loop that is just marking mutations as completed? 
___
*[`internal/sequencer/core/round.go` line 173 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-NtI-83TEe8j8cyPfhsW:-NtI-83UDCfHTGZv1GsT:b-fpla0i) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/17c22d7bd19655459be05324c90ba03d3c8f7d39/internal/sequencer/core/round.go#L173)):*
> ```Go
> 		return err
> 	}
> 	defer func() { _ = stagingTx.Rollback(context.Background()) }()
> ```

Why does stagingTx.Rollback take a context and targetTx.Rollback() doesn't?
___
*[`internal/sequencer/sequtil/copier.go` line 168 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-NtI4ez_DvwFlvVrmN9n:-NtI4ez_DvwFlvVrmN9o:bvj2obd) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/17c22d7bd19655459be05324c90ba03d3c8f7d39/internal/sequencer/sequtil/copier.go#L168)):*
> ```Go
> 		// This will start a timer on the second pass to ensure that
> 		// we flush within a reasonable time period.
> 		goto top
> ```

Might this not create a bunch of timers to close, a not-insignificant number?
___
*[`internal/staging/stage/table_merger.go` line 32 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-NtLp-jDAS9397krl0Xb:-NtLp-jDAS9397krl0Xc:bsnkrrh) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/17c22d7bd19655459be05324c90ba03d3c8f7d39/internal/staging/stage/table_merger.go#L32)):*
> ```Go
> // A mergeBuffer holds working state received from an underlying
> // tableReader channel in order to join mutations by timestamp.
> type mergeBuffer struct {
> ```

Why not attach the cursors to the merge buffer directly instead of passing them in?
___
*[`internal/staging/stage/table_merger.go` line 67 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-NtIsDxu3kNxSYFVHLOF:-NtIsDxu3kNxSYFVHLOG:b-n0oj6l) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/17c22d7bd19655459be05324c90ba03d3c8f7d39/internal/staging/stage/table_merger.go#L67)):*
> ```Go
> 
> // Refresh the buffer from the underlying channel. If the context is
> // null, the refresh will be non-blocking.
> ```

nil :)
___
*[`internal/staging/stage/table_merger.go` line 68 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-NtLnLZS8ZeeprnZVkUU:-NtLnLZS8ZeeprnZVkUV:bt47yiz) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/17c22d7bd19655459be05324c90ba03d3c8f7d39/internal/staging/stage/table_merger.go#L68)):*
> ```Go
> // Refresh the buffer from the underlying channel. If the context is
> // null, the refresh will be non-blocking.
> func (s *mergeBuffer) Refresh(ctx *stopper.Context) error {
> ```

maybe call it stopCtx?  It might be helpful to rename them all throughout the project.  Not right now.
___
*[`internal/staging/stage/table_merger.go` line 230 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-NtNG2Pi0g6nr-YiWWGG:-NtNG2Pi0g6nr-YiWWGH:bojjg7v) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/17c22d7bd19655459be05324c90ba03d3c8f7d39/internal/staging/stage/table_merger.go#L230)):*
> ```Go
> 
> 	// Some buffers are empty. Exit now to force a blocking refresh to
> 	// let db scans catch up.
> ```

Why?  Isn't it possible to have some buffers with no updates?  
___
*[`internal/staging/stage/table_reader.go` line 55 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-NtMaYjmAiX40zmgFdtw:-NtMaYjmAiX40zmgFdtx:b-7j1hjr) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/17c22d7bd19655459be05324c90ba03d3c8f7d39/internal/staging/stage/table_reader.go#L55)):*
> ```Go
> 	scanKey      json.RawMessage        // Position within the table.
> 	sqlQ         string                 // The SQL query that drives the tableReader.
> 	target       ident.Table            // Names of target tables.
> ```

table
___
*[`internal/staging/stage/table_reader.go` line 265 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-NtMyRf-69f7Q4ROmrgV:-NtMyRf06Gti7lnyS0_2:b-o2dxgw) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/17c22d7bd19655459be05324c90ba03d3c8f7d39/internal/staging/stage/table_reader.go#L265)):*
> ```Go
> 		return true
> 	}
> 	// We only allow extensions of existing scans while running.
> ```

Make sure you test the case where you try to extend when not running.

**Review by bobvawter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/767)* status: all files reviewed, 15 unresolved discussions (waiting on @BramGruneir and @sravotto)

___
*[`internal/sequencer/sequencer.go` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-Nt2xQJp0TxZpVQNhCSJ:-NtNR7w84Mcg4SkzOQa1:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/5f61e92a8f74f43577828e8081e7b3fd4c837586/internal/sequencer/sequencer.go#L88)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

language
</blockquote></details>

Done.
___
*[`internal/sequencer/core/core.go` line 279 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-NtHG0pN9SPZzHuITOql:-NtNRBY90OPQ1uXvFS4Z:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/17c22d7bd19655459be05324c90ba03d3c8f7d39/internal/sequencer/core/core.go#L279)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Filer?
</blockquote></details>

Done.
___
*[`internal/sequencer/core/poison.go` line 109 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-NtHMbexC5GlmJNkupMf:-NtNRro3Elmw0gfQGQLX:b-kx749w) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/17c22d7bd19655459be05324c90ba03d3c8f7d39/internal/sequencer/core/poison.go#L109)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This seems to be named really poorly.  It returns if there are new uncontaminated keys that should be contaminated and if there was anything poisoned,
</blockquote></details>

Renamed `toPoison` since it computes work to perform.
___
*[`internal/sequencer/core/poison.go` line 136 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-NtHusYv2FGDwq9GNpuJ:-NtNS5FL9HI2XYNkYfoJ:bgqpdut) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/17c22d7bd19655459be05324c90ba03d3c8f7d39/internal/sequencer/core/poison.go#L136)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

If isPoisoned is false... do we still want to send back this toContaminate batch?
</blockquote></details>

They wouldn't be acted upon, although it's not in keeping with the intent of this method, which is to compute keys that need to be poisoned.
___
*[`internal/sequencer/core/round.go` line 97 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-NtHyeA_5ilYfECciAHs:-NtNeBqs-5usb-f1dyGq:b-5ni5wk) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/17c22d7bd19655459be05324c90ba03d3c8f7d39/internal/sequencer/core/round.go#L97)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Spread?  Contaminate?  IsPoisoned isn't clear that it will cause the contamination to spread.
</blockquote></details>

"Spread" is overloaded with the `...` operator. 
___
*[`internal/sequencer/core/round.go` line 164 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-NtHzfl2AmAh6r1onOIN:-NtNT7S04DcOFTD39CqQ:b-lvtyn5) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/17c22d7bd19655459be05324c90ba03d3c8f7d39/internal/sequencer/core/round.go#L164)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Does this close it?  I don't see the other path unless the Commit itself doesn't always try to commit.
</blockquote></details>

Stale comment. Fixed.
___
*[`internal/sequencer/core/round.go` line 169 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-NtI-M7EEPBiXW0YySlf:-NtNTIfzE6EGu1q_Uegh:bgbci7g) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/17c22d7bd19655459be05324c90ba03d3c8f7d39/internal/sequencer/core/round.go#L169)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Does it make sense to channel these to a different loop that is just marking mutations as completed?
</blockquote></details>

It can't.  I added a comment explaining that a failure to mark the keys as complete needs to poison the keys. Otherwise, you could wind up rolling a key backwards.
___
*[`internal/sequencer/core/round.go` line 173 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-NtI-83TEe8j8cyPfhsW:-NtNU4_F1rmpcjBgo9U1:b43hkda) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/17c22d7bd19655459be05324c90ba03d3c8f7d39/internal/sequencer/core/round.go#L173)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why does stagingTx.Rollback take a context and targetTx.Rollback() doesn't?
</blockquote></details>

Staging uses the `pgx` API, and target uses `sql`.
___
*[`internal/sequencer/sequtil/copier.go` line 168 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-NtI4ez_DvwFlvVrmN9n:-NtNUOQIEX3p_qcBUGLq:b-nkxme6) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/17c22d7bd19655459be05324c90ba03d3c8f7d39/internal/sequencer/sequtil/copier.go#L168)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Might this not create a bunch of timers to close, a not-insignificant number?
</blockquote></details>

The if statement at the top only creates a timer if one has not been created already.
___
*[`internal/staging/stage/table_merger.go` line 32 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-NtLp-jDAS9397krl0Xb:-NtNbBij83F1QE-pc5Zu:b-q3wt1b) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/17c22d7bd19655459be05324c90ba03d3c8f7d39/internal/staging/stage/table_merger.go#L32)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why not attach the cursors to the merge buffer directly instead of passing them in?
</blockquote></details>

Done. The `mergeBuffer` now holds a pointer to the `tableCursor` that it's iterating over.
___
*[`internal/staging/stage/table_merger.go` line 67 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-NtIsDxu3kNxSYFVHLOF:-NtNWLmJ2ZzfdTdy-fJ5:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/17c22d7bd19655459be05324c90ba03d3c8f7d39/internal/staging/stage/table_merger.go#L67)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

nil :)
</blockquote></details>

Done.
___
*[`internal/staging/stage/table_merger.go` line 68 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-NtLnLZS8ZeeprnZVkUU:-NtNWOhP1Qfpapuew3_l:bw9ygdm) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/17c22d7bd19655459be05324c90ba03d3c8f7d39/internal/staging/stage/table_merger.go#L68)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

maybe call it stopCtx?  It might be helpful to rename them all throughout the project.  Not right now.
</blockquote></details>

It's still a `context.Context`, though.
___
*[`internal/staging/stage/table_merger.go` line 230 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-NtNG2Pi0g6nr-YiWWGG:-NtNWmCJ3LvlY959QFaE:b-ntsbz2) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/17c22d7bd19655459be05324c90ba03d3c8f7d39/internal/staging/stage/table_merger.go#L230)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why?  Isn't it possible to have some buffers with no updates?
</blockquote></details>

That actually shouldn't be the case, unless the buffer has advanced to the maximum read time (and all other buffers would also be empty at that maximum time). If we see a mixed case where B1 and B2 have the same non-maximal progress, but B1 is empty and B2 is not, then we know we're still in the middle of filling B1. If there isn't data to be had, B1's progress will jump ahead of B2's progress.  I have finished writing the comment in that second case.
___
*[`internal/staging/stage/table_reader.go` line 55 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-NtMaYjmAiX40zmgFdtw:-NtNbQXt6InkI3gV9Y8E:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/17c22d7bd19655459be05324c90ba03d3c8f7d39/internal/staging/stage/table_reader.go#L55)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

table
</blockquote></details>

Done.
___
*[`internal/staging/stage/table_reader.go` line 265 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-NtMyRf-69f7Q4ROmrgV:-NtNbYbnAFRlj_hwsvTG:bvpnda) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/17c22d7bd19655459be05324c90ba03d3c8f7d39/internal/staging/stage/table_reader.go#L265)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Make sure you test the case where you try to extend when not running.
</blockquote></details>

That's the if block immediately above.

**Comment by bobvawter** [comment]
Filed https://github.com/go-sql-driver/mysql/issues/1567

**Review by sravotto — APPROVED** [review]
:lgtm: However, it was a large PR.  Perhaps having separate PRs for copier, core package and then refactoring of the sequencers would have been easier to review.

> Reviewed 38 of 71 files at r1, 2 of 2 files at r2, 5 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/767#-:-NtQzG1bAxdfY1E0ILQo:b5zupc2)* status: all files reviewed, 15 unresolved discussions (waiting on @BramGruneir)

**Pull request merged**
